# -*- coding: utf-8 -*-
"""Minicurso_SCP02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16iV6CQcMq5XZvxXIxzNkCdnYXMirR1ZP

Minicurso SCP-01 — Assistente de Controle PID com IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/ (cole este .py célula a célula em um
    notebook novo do Google Colab)

===============================================================================
MINICURSO: Sistema de Controle PID com Agente de IA (LangGraph + Groq + RAG)
===============================================================================

Este minicurso constrói, passo a passo, um assistente de engenharia de
controle para uma planta industrial real (sistema de distribuição de água),
combinando:

  Bloco I   — Fundamentos da LLM (Groq)
  Bloco II  — Sistema de Controle (planta RNA caixa-preta + PID)
  Bloco III — Consulta ao RAG (perguntas de teoria com base em PDFs técnicos)
  Bloco IV  — Agente de IA (LangGraph: decide sozinho entre teoria/simular/otimizar)
  Bloco V   — Interface (painel do assistente em Gradio, embutido no notebook)

Antes de começar, configure os segredos no Colab (ícone de chave 🔑 na barra
lateral esquerda):
  - GROQ_API_KEY   — obrigatório, chave da API da Groq.
  - GITHUB_TOKEN   — opcional, Personal Access Token do GitHub (escopo
    `repo`) com leitura em laismngueira/minicurso-smc. Com ele, o início do
    Bloco II clona o repositório sozinho e copia os arquivos de apoio
    (Modelo_AI_v1.h5, DadosTratados.xlsx, os 3 PDFs) para /content/.

Sem GITHUB_TOKEN, envie manualmente pela aba de arquivos do Colab
(/content/) os mesmos arquivos, disponíveis em versao_colab/ neste
repositório:
  - Modelo_AI_v1.h5           (RNA já treinada)
  - DadosTratados.xlsx        (dados reais de campo, usados como contexto fixo)
  - 01_sistema_distribuicao.pdf, 02_sistema_controle.pdf, 03_dados.pdf
    (base de conhecimento do RAG)

O Bloco V não grava nenhum arquivo novo nem sobe processo em segundo
plano: a interface roda dentro do próprio notebook e chama direto os
objetos que os Blocos I-IV já criaram nesta sessão (llm, app, retriever,
simular_planta etc.) — só é preciso ter rodado esses blocos antes.
"""

# ============================================================================
# Bloco I — Fundamentos da LLM
# ============================================================================

"""## Bloco I — Fundamentos da LLM

Toda a parte "inteligente" do sistema (entender uma pergunta em português,
decidir o que fazer, explicar um resultado) é feita por uma LLM (Large
Language Model) hospedada na Groq — um provedor que roda modelos abertos
com inferência muito rápida.

Aqui só validamos a conexão: mandamos uma pergunta simples e conferimos que
a resposta chega.

"""

!pip install -q langchain langchain-groq langgraph

from langchain_groq import ChatGroq
from google.colab import userdata

GROQ_API_KEY = userdata.get('GROQ_API_KEY')

llm = ChatGroq(
    # "llama-3.3-70b-versatile" (usado nas primeiras versões deste minicurso)
    # foi descontinuado pela Groq e não está mais no catálogo — testado em
    # 31/08/2026 (`curl https://api.groq.com/openai/v1/models`). Substituído
    # por um modelo equivalente ainda disponível.
    model="openai/gpt-oss-120b",
    temperature=0.1,
    api_key=GROQ_API_KEY,
)

resp_test = llm.invoke("como funciona o controlador PID em uma planta industrial?")
print(resp_test.content)


# ============================================================================
# Bloco II — Sistema de Controle (planta RNA + PID)
# ============================================================================

"""## Bloco II — Sistema de Controle

### A planta: uma RNA treinada com dados reais

A "planta" deste minicurso não é uma fórmula matemática — é uma **Rede
Neural Artificial (RNA)** treinada com dados reais de campo de um sistema de
distribuição de água (bomba centrífuga + inversor de frequência + rede
hidráulica). Ela recebe a frequência do inversor (a variável que o PID
manipula) e devolve a pressão prevista na rede (PT_4A). Para o PID, ela é só
uma caixa-preta: entra um sinal de controle, sai uma medição — o que
acontece por dentro (as 3 camadas da rede) não importa aqui.

Como as demais variáveis medidas (outras pressões e vazões da planta) também
influenciam a leitura de pressão e não são controladas por nós, usamos uma
linha real do conjunto de dados como "estado_base" fixo — só a coluna do
inversor é alterada pelo controlador.

### O controlador: PID em forma paralela

Usamos a forma paralela do PID (ganhos Kp, Ki, Kd diretos — sem passar por
constantes de tempo Ti/Td):

    saida = Kp*erro + Ki*integral + Kd*derivada

E aplicamos essa saída de forma **incremental** sobre o próprio sinal de
controle anterior (`u += saida`, com saturação) — é assim que a planta real
é operada: o inversor não "salta" para um novo valor absoluto a cada
amostra, ele é ajustado a partir do valor em que já está.

Os ganhos padrão (Kp=1, Ki=0.1, Kd=0.05) e o cenário de teste (setpoint
5.0 → 6.0 → 4.0, a cada 400 amostras, com passo de amostragem de 1s) foram
validados manualmente e reproduzem o comportamento documentado no projeto de
referência (PID_Aut_Inteligente).

### Baixando os arquivos de apoio (RNA, dataset, PDFs)

Em vez de enviar manualmente Modelo_AI_v1.h5, DadosTratados.xlsx e os PDFs
pela aba de arquivos toda vez que abrir uma sessão nova (o `/content/` do
Colab é apagado quando a sessão desconecta), esta célula clona o repositório
do GitHub e copia tudo de uma vez.

Requisito: configure um segredo `GITHUB_TOKEN` no Colab (ícone de chave 🔑
na barra lateral esquerda) com um Personal Access Token do GitHub (escopo
`repo`, já que este é um repositório privado — gere um em
https://github.com/settings/tokens, de preferência um *fine-grained token*
com acesso restrito só a este repositório). Se o segredo não estiver
configurado, a célula avisa e você pode enviar os arquivos manualmente como
alternativa.
"""

from pathlib import Path

from google.colab import userdata

try:
    GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')
except Exception:
    GITHUB_TOKEN = None

REPO_DIR = Path("/content/minicurso-smc")
ARQUIVOS_APOIO = [
    "Modelo_AI_v1.h5", "DadosTratados.xlsx",
    "01_sistema_distribuicao.pdf", "02_sistema_controle.pdf", "03_dados.pdf",
]

if GITHUB_TOKEN and not REPO_DIR.exists():
    import os
    os.environ["GITHUB_TOKEN"] = GITHUB_TOKEN
    !git clone -q https://x-access-token:$GITHUB_TOKEN@github.com/laismngueira/minicurso-smc.git {REPO_DIR}
    origem = REPO_DIR / "versao_colab"
    for nome in ARQUIVOS_APOIO:
        !cp "{origem / nome}" /content/
    print("Arquivos de apoio copiados de", origem, "para /content/:")
    !ls -la /content/*.h5 /content/*.xlsx /content/*.pdf
elif GITHUB_TOKEN:
    print("Repositório já clonado em", REPO_DIR, "— nada a fazer.")
else:
    print(
        "Segredo GITHUB_TOKEN não configurado. Envie manualmente pela aba de "
        "arquivos do Colab: " + ", ".join(ARQUIVOS_APOIO)
    )

!pip install -q sentence-transformers langchain_community

# Aquecimento "silencioso" do PyTorch, ANTES de importar o TensorFlow: as
# duas bibliotecas usam runtimes nativos (OpenMP/MKL) que entram em conflito
# (segfault) se carregadas na ordem errada no mesmo processo — e um simples
# `import torch` não basta, é preciso inicializar de verdade um modelo (o
# Bloco III usa exatamente este `HuggingFaceEmbeddings` para o RAG). Isso
# não tem relação com a planta em si; é só uma particularidade do ambiente,
# então plugamos aqui antes de tocar no TensorFlow.
from langchain_community.embeddings import HuggingFaceEmbeddings

_aquecimento_pytorch = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
_aquecimento_pytorch.embed_query("aquecimento")
del _aquecimento_pytorch

!pip install -q tensorflow scikit-learn pandas openpyxl matplotlib

import base64
import io
import warnings

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import load_model

warnings.filterwarnings("ignore", message="X does not have valid feature names")

def _localizar_arquivo(nome):
    encontrados = list(Path("/content/").glob(nome))
    if not encontrados:
        raise FileNotFoundError(
            f"Arquivo '{nome}' não encontrado em /content/. Configure o "
            "segredo GITHUB_TOKEN (célula acima) ou envie o arquivo "
            "manualmente pela aba de arquivos do Colab antes de continuar."
        )
    return encontrados[0]


modelo = load_model(_localizar_arquivo("Modelo_AI_v1.h5"))
dados = pd.read_excel(_localizar_arquivo("DadosTratados.xlsx"))

COLUNAS_ENTRADA = [
    "Inversor", "PT_1B", "PT_1C", "PT_1D", "PT_2A", "PT_2B",
    "PT_2C", "PT_3A", "PT_5A", "FT_1A", "FT_3A", "FT_4A", "FT_6A",
]
IDX_VARIAVEL_MANIPULADA = 0  # 'Inversor': frequência do inversor, ação do PID
LIMITE_INF_U, LIMITE_SUP_U = 0.0, 100.0  # faixa operacional do inversor (Hz)

X = dados[COLUNAS_ENTRADA]

# scaler ajustado no dataset inteiro (mesma normalização usada no treino da RNA)
scaler = StandardScaler()
scaler.fit(X)

estado_base = X.iloc[0].values.copy()

"""### Testando a planta isoladamente

Antes de fechar a malha, vale ver como a RNA responde a diferentes valores
de frequência do inversor — isso ajuda a entender por que os ganhos do PID
precisam ser pequenos: a curva da planta não é linear, e em algumas faixas
(acima de ~50Hz) o ganho (variação de pressão por Hz) é bem mais alto.

"""

import warnings

def planta_caixa_preta(u):
    """Caixa-preta: aplica o sinal de controle 'u' (frequência do inversor)
    e devolve a pressão medida na planta real, prevista pela RNA."""
    entrada = estado_base.copy()
    entrada[IDX_VARIAVEL_MANIPULADA] = np.clip(u, LIMITE_INF_U, LIMITE_SUP_U)
    entrada_escalada = scaler.transform([entrada]).astype("float32")
    y_pred = modelo(entrada_escalada, training=False).numpy()[0][0]
    return float(y_pred)


print("Curva estática da planta (u -> pressão prevista):")
for u_teste in [0, 20, 40, 50, 60, 80, 100]:
    print(f"  u={u_teste:5.1f} Hz  ->  y={planta_caixa_preta(u_teste):.3f}")
    warnings.filterwarnings("ignore", message="X does not have valid feature names")

"""### Fechando a malha: simulação com o PID

`simular_planta` roda o laço fechado por `N_amostras` passos, aplicando o
PID incremental a cada amostra e registrando a resposta. Ao final, calcula
métricas clássicas de desempenho (overshoot, tempo de acomodação, erro
final, ISE, IAE, ITAE) e devolve tudo num dicionário — inclusive o gráfico,
já pronto em base64 para ser exibido depois na interface.

"""

def simular_planta(Kp=1.0, Ki=0.1, Kd=0.05, T_amostragem=1.0, N_amostras=1200, plot=True):
    segmento = N_amostras // 3
    yr = np.zeros(N_amostras)
    y_med = np.zeros(N_amostras)
    yr[0:segmento] = 5.0
    yr[segmento:2 * segmento] = 6.0
    yr[2 * segmento:3 * segmento] = 4.0

    y = np.zeros(N_amostras)
    u = np.zeros(N_amostras)
    erro = np.zeros(N_amostras)

    # o atuador começa no valor de "Inversor" da própria linha usada como
    # estado_base (não em zero) — e a cada troca de setpoint o integrador e
    # o erro anterior são reiniciados (equivalente a recriar o controlador
    # PID a cada novo degrau, como no projeto de referência).
    u_atual = float(estado_base[IDX_VARIAVEL_MANIPULADA])
    integral_acc = 0.0
    erro_anterior = 0.0

    for k in range(N_amostras):
        if k == segmento or k == 2 * segmento:
            integral_acc = 0.0
            erro_anterior = 0.0

        u[k] = u_atual
        y[k] = planta_caixa_preta(u_atual)
        y_med[k] = y[k]  # ruído desligado (some com 0.0; ver comentário abaixo)
        erro[k] = yr[k] - y_med[k]

        # PID em forma paralela: saida = Kp*erro + Ki*integral + Kd*derivada
        integral_acc += erro[k] * T_amostragem
        derivada = (erro[k] - erro_anterior) / T_amostragem
        erro_anterior = erro[k]
        controle = Kp * erro[k] + Ki * integral_acc + Kd * derivada

        # incremental: soma-se ao valor anterior do atuador, não recalcula do zero
        u_atual = np.clip(u_atual + controle, LIMITE_INF_U, LIMITE_SUP_U)

    tempo = np.arange(0, N_amostras) * T_amostragem

    ise = np.sum(erro**2) * T_amostragem
    iae = np.sum(np.abs(erro)) * T_amostragem
    itae = np.sum(tempo * np.abs(erro)) * T_amostragem

    y_segment = y_med[:segmento]
    ref = yr[0]
    overshoot = (np.max(y_segment) - ref) / ref * 100 if np.max(y_segment) > ref else 0
    erro_final = abs(ref - y_segment[-1])

    sup, inf = ref * 1.02, ref * 0.98
    indices_fora = np.where((y_segment < inf) | (y_segment > sup))[0]
    tempo_acomod = tempo[indices_fora[-1] + 1] if len(indices_fora) else tempo[0]

    img64 = None
    if plot:
        fig, ax = plt.subplots(figsize=(9, 4))
        ax.plot(tempo, y, linewidth=1.2, label="Variável Controlada")
        ax.plot(tempo, yr, "--", linewidth=1.0, label="Setpoint")
        ax.set_title(f"PID | Kp={Kp:.2f} Ki={Ki:.2f} Kd={Kd:.2f}")
        ax.set_xlabel("Tempo (s)")
        ax.set_ylabel("Amplitude")
        ax.grid(True)
        ax.legend()
        plt.show()

        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        buf.seek(0)
        img64 = base64.b64encode(buf.getvalue()).decode("utf-8")
        plt.close(fig)

    return {
        "Kp": Kp, "Ki": Ki, "Kd": Kd,
        "overshoot": round(overshoot, 2),
        "tempo_acomod": round(float(tempo_acomod), 2),
        "erro_final": round(erro_final, 4),
        "referencia": float(ref),
        "ise": round(ise, 2),
        "iae": round(iae, 2),
        "itae": round(itae, 2),
        "grafico": img64,
    }


resultados = simular_planta()
warnings.filterwarnings("ignore", message="X does not have valid feature names")

"""### Resultados no cenário padrão (Kp=1, Ki=0.1, Kd=0.05)

"""

print("\n" + "=" * 30)
print("  RESULTADOS DO CONTROLE PID")
print("=" * 30)
for chave, valor in resultados.items():
    if chave != "grafico":
        print(f"{chave:15}: {valor}")
print("=" * 30)

"""### Otimização automática dos ganhos

`buscar_melhores_parametros` faz uma busca em grade (grid search) — testa
várias combinações de Kp/Ki/Kd e fica com a que minimiza
`ISE + 2*overshoot` (a penalidade em overshoot evita escolher ganhos
agressivos demais só porque reduzem o erro acumulado). Cada simulação chama
a RNA de verdade 1200 vezes, então essa busca é bem mais lenta que uma
simulação única — a grade aqui já foi reduzida (4×4×3 = 48 combinações) para
caber em poucos minutos.

"""

def buscar_melhores_parametros():
    melhor, melhor_custo = None, 1e9
    for kp in np.linspace(0.2, 3.0, 4):
        for ki in np.linspace(0.02, 0.3, 4):
            for kd in np.linspace(0.0, 0.2, 3):
                try:
                    r = simular_planta(kp, ki, kd, plot=False)
                    custo = r["ise"] + 2 * r["overshoot"]
                    if np.isnan(custo) or np.isinf(custo):
                        continue
                    if custo < melhor_custo:
                        melhor_custo, melhor = custo, r
                except Exception:
                    continue
    if melhor is None:
        return None
    return simular_planta(melhor["Kp"], melhor["Ki"], melhor["Kd"], plot=True)


def simular_com_protecao_overshoot(kp, ki, kd):
    """Reduz Kp/Kd iterativamente se o overshoot passar de 30%."""
    kp = max(0.0, min(kp, 50.0))
    ki = max(0.0, min(ki, 1.0))
    kd = max(0.0, min(kd, 20.0))

    fator_reducao = 0.7
    melhor = None
    for _ in range(5):
        try:
            resultado = simular_planta(Kp=kp, Ki=ki, Kd=kd, plot=False)
            overshoot = resultado["overshoot"]
            if np.isnan(overshoot) or np.isinf(overshoot):
                raise ValueError("Overshoot inválido")
            melhor = resultado
            if overshoot <= 30:
                break
            kp *= fator_reducao
            kd *= fator_reducao
        except Exception:
            kp *= fator_reducao
            kd *= fator_reducao

    if melhor is None:
        return {
            "Kp": kp, "Ki": ki, "Kd": kd,
            "overshoot": None, "tempo_acomod": None, "erro_final": None,
            "ise": None, "iae": None, "itae": None, "grafico": None,
            "erro": "Falha na simulação",
        }
    return simular_planta(Kp=melhor["Kp"], Ki=melhor["Ki"], Kd=melhor["Kd"], plot=True)


# Descomente para rodar a otimização (leva alguns minutos):
# melhor_resultado = buscar_melhores_parametros()
# print(melhor_resultado)


# ============================================================================
# Bloco III — Consulta ao RAG
# ============================================================================

"""## Bloco III — Consulta ao RAG (Retrieval-Augmented Generation)

Para perguntas de **teoria** (o que é overshoot? qual o papel do termo
derivativo?), não queremos que a LLM "invente" uma resposta genérica —
queremos que ela responda com base em documentos técnicos reais.

O RAG faz isso em 4 passos:
  1. Lê todos os PDFs de `/content/`.
  2. Quebra cada PDF em pedaços pequenos (chunks), com uma leve sobreposição
     entre eles para não perder contexto nas bordas.
  3. Transforma cada chunk em um vetor numérico (embedding) e indexa tudo
     num banco vetorial (FAISS).
  4. Na hora da pergunta, busca os chunks mais parecidos com a pergunta e
     manda só esses trechos (não o PDF inteiro) para a LLM responder.

"""

!pip install -q --upgrade langchain langchain_community faiss-cpu langchain-text-splitters pymupdf sentence-transformers

from pathlib import Path

from langchain_community.document_loaders import PyMuPDFLoader

docs = []
for n in Path("/content/").glob("*.pdf"):
    try:
        loader = PyMuPDFLoader(str(n))
        docs.extend(loader.load())
        print(f"Carregado com sucesso arquivo {n.name}")
    except Exception as e:
        print(f"Erro ao carregar arquivo {n.name}: {e}")

print(f"Total de páginas carregadas: {len(docs)}")

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(chunk_size=400, chunk_overlap=40)
chunks = splitter.split_documents(docs)
print(f"Total de chunks gerados: {len(chunks)}")

from langchain_community.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

from langchain_community.vectorstores import FAISS

vectorstore = FAISS.from_documents(chunks, embeddings)
retriever = vectorstore.as_retriever(
    search_type="similarity_score_threshold",
    search_kwargs={"score_threshold": 0.15, "k": 4},
)

from langchain_core.prompts import ChatPromptTemplate

prompt_rag = ChatPromptTemplate.from_messages([
    ("system",
     "Você é um assistente especialista em sistemas de controle em malha fechada "
     "aplicados a processos industriais.\n\n"
     "Seu conhecimento baseia-se em documentos técnicos sobre:\n"
     "- Controle PID\n- Métricas de desempenho (ISE, IAE, ITAE, overshoot)\n"
     "- Modelagem de plantas\n- Discretização de sistemas (ZOH)\n"
     "- Controle de pressão em sistemas de distribuição de água\n\n"
     "A saída do sistema corresponde à pressão da rede hidráulica.\n\n"
     "Responda SOMENTE com base no contexto fornecido.\n"
     "Se não houver informação suficiente no contexto, responda apenas: 'Não sei'."),
    ("human", "Pergunta: {input}\n\nContexto técnico:\n{context}"),
])

from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

document_chain = (
    {"context": lambda x: x["context"], "input": RunnablePassthrough()}
    | prompt_rag | llm | StrOutputParser()
)

import re


def _clean_text(s):
    return re.sub(r"\s+", " ", s or "").strip()


def extrair_trecho(texto, query, janela=240):
    txt = _clean_text(texto)
    termos = [t.lower() for t in re.findall(r"\w+", query or "") if len(t) >= 4]
    pos = -1
    for t in termos:
        pos = txt.lower().find(t)
        if pos != -1:
            break
    if pos == -1:
        pos = 0
    ini = max(0, pos - janela // 2)
    fim = min(len(txt), pos + janela // 2)
    return txt[ini:fim]


def formatar_citacoes(docs_rel, query):
    cites, seen = [], set()
    for d in docs_rel:
        src = Path(d.metadata.get("source", "")).name
        page = int(d.metadata.get("page", 0)) + 1
        key = (src, page)
        if key in seen:
            continue
        seen.add(key)
        cites.append({"documento": src, "pagina": page, "trecho": extrair_trecho(d.page_content, query)})
    return cites[:3]


def perguntar_controle_rag(pergunta):
    docs_relacionados = retriever.invoke(pergunta)
    if not docs_relacionados:
        return {"answer": "Não sei.", "citacoes": [], "contexto_encontrado": False}

    answer = document_chain.invoke({"input": pergunta, "context": docs_relacionados})
    txt = (answer or "").strip()

    if txt.rstrip(".!?") == "Não sei":
        return {"answer": "Não sei.", "citacoes": [], "contexto_encontrado": False}

    return {
        "answer": txt,
        "citacoes": formatar_citacoes(docs_relacionados, pergunta),
        "contexto_encontrado": True,
    }

"""### Testando o RAG

"""

testes_rag = [
    "O que é overshoot em sistemas de controle em malha fechada?",
    "Qual é o papel do termo derivativo em um controlador PID?",
    "O que é o método Zero Order Hold (ZOH) e por que ele é usado na discretização da planta?",
]

for msg_teste in testes_rag:
    resposta = perguntar_controle_rag(msg_teste)
    print("-" * 40)
    print(f"PERGUNTA: {msg_teste}")
    print(f"RESPOSTA: {resposta['answer']}")
    if resposta["contexto_encontrado"]:
        print("CITAÇÕES:")
        for c in resposta["citacoes"]:
            print(f" - {c['documento']}, pág. {c['pagina']}")


# ============================================================================
# Bloco IV — Agente de IA (LangGraph)
# ============================================================================

"""## Bloco IV — Agente de IA

Até aqui temos três "ferramentas" separadas: o simulador de PID (Bloco II),
o RAG de teoria (Bloco III), e a LLM crua (Bloco I). O agente é a peça que
decide sozinha **qual** ferramenta usar, a partir de uma única pergunta em
linguagem natural.

O grafo de estados (LangGraph) funciona assim:

    START -> triagem -> [decide]
                          |-- TEORIA   -> teoria (RAG)     -> llm -> END
                          |-- SIMULAR  -> simular           -> resposta_final -> llm -> END
                          |-- OTIMIZAR -> otimizar           -> resposta_final -> llm -> END

O nó `triagem` usa a LLM com **saída estruturada** (um schema Pydantic) para
classificar a pergunta e já extrair, se houver, os valores de Kp/Ki/Kd
mencionados pelo usuário. O nó `llm`, no final, reescreve a resposta de
forma didática — mas com uma regra importante: se a pergunta era sobre
simular/otimizar, ele **não** pode reabrir uma aula de teoria sobre PID, só
reportar os números obtidos.

"""

!pip install -q --upgrade langgraph

from typing import Dict, List, Literal, Optional, TypedDict

from langchain_core.messages import HumanMessage, SystemMessage
from langgraph.graph import END, START, StateGraph
from pydantic import BaseModel

TRIAGEM_PROMPT = (
    "Você é um agente de triagem para um assistente de engenharia de controle "
    "utilizado em uma planta industrial em malha fechada.\n\n"
    "O sistema possui três funcionalidades principais:\n"
    "1) Responder perguntas teóricas sobre controle e PID\n"
    "2) Simular o comportamento da planta com parâmetros fornecidos\n"
    "3) Otimizar os parâmetros do controlador para melhorar o desempenho\n\n"
    "Dada a mensagem do usuário, retorne SOMENTE um JSON no formato:\n"
    "{\n"
    '  "decisao": "TEORIA" | "SIMULAR" | "OTIMIZAR",\n'
    '  "kp": float | null,\n'
    '  "ki": float | null,\n'
    '  "kd": float | null,\n'
    '  "ganho_alvo": float | null,\n'
    '  "erro_alvo": float | null\n'
    "}\n\n"
    "Regras de classificação:\n"
    "- **TEORIA**: perguntas conceituais sobre controle, PID ou comportamento de sistemas.\n"
    "- **SIMULAR**: quando o usuário fornece valores de controlador e deseja ver o comportamento da planta. "
    "Valores podem ser ZERO (0) e devem ser mantidos.\n"
    "- **OTIMIZAR**: quando o usuário quer encontrar automaticamente os parâmetros do controlador.\n"
    "Se um parâmetro não estiver presente na mensagem, retorne null."
)


class TriagemOut(BaseModel):
    decisao: Literal["TEORIA", "SIMULAR", "OTIMIZAR"]
    kp: Optional[float] = None
    ki: Optional[float] = None
    kd: Optional[float] = None
    ganho_alvo: Optional[float] = None
    erro_alvo: Optional[float] = None


triagem_chain = llm.with_structured_output(TriagemOut, method="json_mode")


def triagem(mensagem):
    saida: TriagemOut = triagem_chain.invoke([
        SystemMessage(content=TRIAGEM_PROMPT),
        HumanMessage(content=mensagem),
    ])
    return saida.model_dump()

"""### Testando só a triagem (antes de montar o grafo)

"""

testes = [
    "o que é overshoot em sistemas de controle?",
    "simule a planta com kp=1.5 ki=0.1 kd=0.05",
    "otimize os parâmetros do PID para minimizar erro",
]

for msg_teste in testes:
    print(f"Pergunta: {msg_teste}\n -> Resposta: {triagem(msg_teste)}\n")


class AgentState(TypedDict, total=False):
    pergunta: str
    classificacao: str
    parametros: dict
    resultado: dict
    resposta_tecnica: str
    resposta: str
    citacoes: list


def node_triagem(state: AgentState) -> AgentState:
    print("\n🔎 Executando nó de triagem...")
    saida = triagem(state["pergunta"])
    classificacao = saida["decisao"].upper().strip()
    print("Classificação:", classificacao)
    parametros = {
        "kp": saida.get("kp"), "ki": saida.get("ki"), "kd": saida.get("kd"),
        "ganho_alvo": saida.get("ganho_alvo"), "erro_alvo": saida.get("erro_alvo"),
    }
    return {**state, "classificacao": classificacao, "parametros": parametros}


def node_teoria(state: AgentState) -> AgentState:
    print("\n📚 Executando nó de teoria (RAG)...")
    pergunta = state["pergunta"]
    rag_resp = perguntar_controle_rag(pergunta)
    print("RAG encontrou contexto:", rag_resp["contexto_encontrado"])

    if rag_resp["contexto_encontrado"]:
        resposta_final, citacoes = rag_resp["answer"], rag_resp["citacoes"]
    else:
        prompt = f"""
Você é um especialista em sistemas de controle em malha fechada.

Explique a pergunta abaixo de forma clara para um estudante de engenharia elétrica.

Pergunta:
{pergunta}

Observação:
Não foram encontrados documentos na base de conhecimento.
Responda com base apenas no conhecimento geral de engenharia de controle.
"""
        resposta_llm = llm.invoke(prompt)
        resposta_final, citacoes = resposta_llm.content, []

    return {**state, "resposta": resposta_final, "citacoes": citacoes}


def node_simular(state: AgentState) -> AgentState:
    print("\n⚙️ Executando simulação PID...")
    p = state["parametros"]
    kp = p.get("kp") if p.get("kp") is not None else 1.0
    ki = p.get("ki") if p.get("ki") is not None else 0.1
    kd = p.get("kd") if p.get("kd") is not None else 0.05
    resultado_final = simular_com_protecao_overshoot(kp, ki, kd)
    return {**state, "resultado": resultado_final}


def node_otimizar(state: AgentState) -> AgentState:
    print("\n🧠 Executando otimização...")
    melhor_final = buscar_melhores_parametros()
    return {**state, "resultado": melhor_final}


def node_resposta_final(state: AgentState) -> AgentState:
    print("\n📊 Gerando resposta técnica...")
    r = state["resultado"]
    texto = f"""
Simulação PID realizada.

Parâmetros do controlador:
Kp = {r["Kp"]}
Ki = {r["Ki"]}
Kd = {r["Kd"]}

Métricas:
Overshoot: {r["overshoot"]} %
Tempo de acomodação: {r["tempo_acomod"]} s
Erro final: {r["erro_final"]}

ISE: {r["ise"]}
IAE: {r["iae"]}
ITAE: {r["itae"]}
"""
    return {**state, "resposta_tecnica": texto}


def node_llm(state: AgentState) -> AgentState:
    print("\n🤖 Refinando resposta com LLM...")
    classificacao = state.get("classificacao")

    if classificacao in ("SIMULAR", "OTIMIZAR"):
        texto = state.get("resposta_tecnica", "")
        acao = "SIMULAÇÃO" if classificacao == "SIMULAR" else "OTIMIZAÇÃO"
        prompt = f"""
Você é um especialista em sistemas de controle industrial.

Abaixo está o resultado de uma {acao} de um controlador PID que já foi
executada. Use exatamente essa palavra ({acao.lower()}) ao se referir ao que
foi feito — não troque por outro termo.

Apresente esse resultado de forma limpa, mantendo EXATAMENTE os valores
numéricos informados (não invente nem arredonde diferente do que está aqui).

Adicione no máximo 2-3 frases de comentário técnico ESPECÍFICO sobre este
resultado (por exemplo, se o overshoot está alto, se o erro final é
satisfatório, se a sintonia parece adequada).

NÃO explique conceitos gerais de controle PID (o que é Kp, Ki, Kd, overshoot,
ISE, IAE, ITAE etc.) — o usuário já pediu uma {acao.lower()}, não uma aula de
teoria. Seja direto e objetivo.

Resultado:
{texto}
"""
    else:
        texto = state.get("resposta_tecnica", state.get("resposta", ""))
        prompt = f"""
Você é um especialista em sistemas de controle.

Explique o conteúdo abaixo de forma clara e didática, em texto corrido e
tabelas quando fizer sentido.

NÃO inclua seções como "resumo visual", "diagrama", "esquema" ou qualquer
tentativa de desenhar um diagrama/gráfico usando apenas texto ou caracteres
ASCII — isso não é um diagrama de verdade, só texto tentando parecer um, e
fica quebrado. Se quiser ilustrar algo visualmente, descreva em palavras ou
use uma tabela.

{texto}
"""
    resposta = llm.invoke(prompt)
    return {**state, "resposta": resposta.content}


workflow = StateGraph(AgentState)
workflow.add_node("triagem", node_triagem)
workflow.add_node("simular", node_simular)
workflow.add_node("teoria", node_teoria)
workflow.add_node("otimizar", node_otimizar)
workflow.add_node("resposta_final", node_resposta_final)
workflow.add_node("llm", node_llm)

workflow.add_edge(START, "triagem")
workflow.add_conditional_edges(
    "triagem", lambda x: x["classificacao"],
    {"SIMULAR": "simular", "TEORIA": "teoria", "OTIMIZAR": "otimizar"},
)
workflow.add_edge("simular", "resposta_final")
workflow.add_edge("otimizar", "resposta_final")
workflow.add_edge("resposta_final", "llm")
workflow.add_edge("teoria", "llm")
workflow.add_edge("llm", END)

app = workflow.compile()

"""### Fluxograma do agente

"""

from IPython.display import Image, display

graph_bytes = app.get_graph().draw_mermaid_png()
display(Image(graph_bytes))

"""### Testando o agente completo

"""

pergunta = "simule a planta com kp=1 ki=0.1 kd=0.05"

resultado = app.invoke({"pergunta": pergunta}, config={"recursion_limit": 10})

print("\n" + "=" * 30)
print("RESPOSTA DO SISTEMA")
print("=" * 30 + "\n")
print(resultado["resposta"])


# ============================================================================
# Bloco V — Interface (painel do assistente, embutido no notebook)
# ============================================================================

"""## Bloco V — Interface

Nada da planta, do PID, do RAG ou do agente é reescrito aqui: a interface
só chama, diretamente, os mesmos objetos que os Blocos I-IV desta sessão já
criaram e validaram — `llm` (Bloco I), `simular_planta` /
`simular_com_protecao_overshoot` / `buscar_melhores_parametros` (Bloco II),
`perguntar_controle_rag` (Bloco III) e `app`, o workflow do LangGraph
(Bloco IV). Não há `%%writefile`, nenhum arquivo novo é gravado e nenhum
processo sobe em segundo plano — a interface roda no mesmo processo
Python que já rodou os blocos anteriores.

Isso também evita a classe de bug mais comum de rodar a interface como um
processo separado (ex.: Streamlit): como aqui tudo roda no mesmo kernel,
não é preciso repassar a `GROQ_API_KEY` por variável de ambiente nem
recarregar a RNA/o índice do RAG — `llm`, `modelo` e `retriever` já estão
prontos na memória.

Usamos o [Gradio](https://gradio.app), que tem suporte nativo ao Colab:
`demo.launch()` sobe um link público (`https://xxxx.gradio.live`), válido
por 72h, sem precisar de `npm install`, senha ou proxy manual — é a forma
oficialmente recomendada pelo próprio Gradio para notebooks no Colab.
"""

!pip install -q -U gradio

import base64
import io

import gradio as gr
from PIL import Image


def formatar_metricas(r):
    """Reaproveita o dicionário devolvido por simular_planta/
    simular_com_protecao_overshoot/buscar_melhores_parametros (Bloco II) —
    mesmas chaves, sem recalcular nada."""
    if not r or r.get("overshoot") is None:
        return "_Nenhuma simulação executada ainda._"
    return (
        f"**Kp:** {r['Kp']:.3f}   **Ki:** {r['Ki']:.3f}   **Kd:** {r['Kd']:.3f}\n\n"
        f"**Overshoot:** {r['overshoot']:.2f} %  \n"
        f"**Erro final:** {r['erro_final']:.4f}  \n"
        f"**Tempo de acomodação:** {r['tempo_acomod']:.2f} s  \n"
        f"**ISE:** {r['ise']:.2f}   **IAE:** {r['iae']:.2f}   **ITAE:** {r['itae']:.2f}"
    )


def imagem_do_resultado(r):
    """O gráfico já vem pronto em base64 dentro do resultado (Bloco II) —
    só decodifica para exibir no componente de imagem do Gradio."""
    if not r or not r.get("grafico"):
        return None
    return Image.open(io.BytesIO(base64.b64decode(r["grafico"])))


def acao_simular(kp, ki, kd):
    r = simular_com_protecao_overshoot(kp, ki, kd)
    return formatar_metricas(r), imagem_do_resultado(r)


def acao_otimizar():
    r = buscar_melhores_parametros()
    return formatar_metricas(r), imagem_do_resultado(r)


def responder_chat(mensagem, historico):
    if not mensagem or not mensagem.strip():
        return historico, "", gr.update(), gr.update()

    resultado = app.invoke({"pergunta": mensagem}, config={"recursion_limit": 10})
    resposta = resultado.get("resposta") or "Sem resposta."
    citacoes = resultado.get("citacoes", [])
    if citacoes:
        resposta += "\n\n**Citações técnicas:**\n" + "\n".join(
            f"- {c['documento']}, pág. {c['pagina']}: _{c['trecho']}_" for c in citacoes
        )

    historico = historico + [[mensagem, resposta]]

    if resultado.get("resultado"):
        texto_m = formatar_metricas(resultado["resultado"])
        img_m = imagem_do_resultado(resultado["resultado"])
    else:
        texto_m, img_m = gr.update(), gr.update()

    return historico, "", texto_m, img_m


def limpar_conversa():
    return []


with gr.Blocks(title="Assistente de Controle PID") as demo:
    gr.Markdown(
        "# 🏭 Assistente de Controle PID — Sistema de Distribuição de Água\n"
        "Planta: RNA treinada com dados reais de campo (PT_4A)."
    )

    with gr.Row():
        with gr.Column(scale=3):
            gr.Markdown("### 💬 Assistente (IA)")
            chatbot = gr.Chatbot(
                value=[[None, (
                    'Aguardando comando. Pergunte algo (ex.: "o que é overshoot?"), '
                    'peça uma simulação ("simule a planta com kp=1 ki=0.1 kd=0.05") '
                    'ou uma otimização ("otimize os parâmetros").'
                )]],
                height=420,
                label="Conversa",
            )
            caixa_mensagem = gr.Textbox(
                placeholder='Digite sua pergunta ou comando (ex.: "simule a planta com kp=1 ki=0.1 kd=0.05")...',
                show_label=False,
            )
            with gr.Row():
                botao_enviar = gr.Button("Enviar", variant="primary")
                botao_limpar = gr.Button("🗑️ Limpar conversa")

        with gr.Column(scale=2):
            gr.Markdown("### 🎛️ Painel Manual")
            slider_kp = gr.Slider(0.0, 50.0, value=1.0, step=0.1, label="Kp")
            slider_ki = gr.Slider(0.0, 1.0, value=0.1, step=0.01, label="Ki")
            slider_kd = gr.Slider(0.0, 1.0, value=0.05, step=0.01, label="Kd")
            with gr.Row():
                botao_simular = gr.Button("▶ Simular", variant="primary")
                botao_otimizar = gr.Button("🔍 Otimizar")

            gr.Markdown("### 📊 Métricas")
            # Cenário padrão: reaproveita `resultados`, já calculado no Bloco
            # II (Kp=1, Ki=0.1, Kd=0.05) — não roda uma nova simulação só
            # para popular o painel.
            texto_metricas = gr.Markdown(formatar_metricas(resultados))
            gr.Markdown("### 📈 Tendência")
            imagem_grafico = gr.Image(
                value=imagem_do_resultado(resultados), show_label=False
            )

    caixa_mensagem.submit(
        responder_chat,
        [caixa_mensagem, chatbot],
        [chatbot, caixa_mensagem, texto_metricas, imagem_grafico],
    )
    botao_enviar.click(
        responder_chat,
        [caixa_mensagem, chatbot],
        [chatbot, caixa_mensagem, texto_metricas, imagem_grafico],
    )
    botao_limpar.click(limpar_conversa, [], [chatbot])
    botao_simular.click(
        acao_simular, [slider_kp, slider_ki, slider_kd], [texto_metricas, imagem_grafico]
    )
    botao_otimizar.click(acao_otimizar, [], [texto_metricas, imagem_grafico])

demo.launch()

"""### Solução de problemas

- Se `demo.launch()` não imprimir nenhum link: rode a célula de novo — às
  vezes a primeira chamada falha só por timing na criação do túnel do
  Gradio.
- Se o chat responder com erro: confirme que os Blocos I-IV rodaram sem
  erro antes deste (a interface depende de `llm`, `app`, `retriever`,
  `modelo` já existirem na sessão — reinicie o ambiente de execução e rode
  os blocos em ordem se precisar).
- Se quiser encerrar o painel (por exemplo, antes de rodar a célula de
  novo): `demo.close()` numa célula separada.
- Link expirado (72h) ou sessão do Colab reiniciada: basta rodar esta
  célula de novo — um novo link é gerado.
"""
