# -*- coding: utf-8 -*-
"""Minicurso SCP-01 — Assistente de Controle PID com IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/ (cole este .py célula a célula em um
    notebook novo do Google Colab)

===============================================================================
MINICURSO: Sistema de Controle PID com Agente de IA (LangGraph + Groq + RAG)
===============================================================================

Este minicurso constrói, passo a passo, um assistente de engenharia de
controle para uma planta industrial real (sistema de distribuição de água),
combinando:

  Bloco I   — Fundamentos da LLM (Groq)
  Bloco II  — Sistema de Controle (planta RNA caixa-preta + PID)
  Bloco III — Consulta ao RAG (perguntas de teoria com base em PDFs técnicos)
  Bloco IV  — Agente de IA (LangGraph: decide sozinho entre teoria/simular/otimizar)
  Bloco V   — Interface (painel industrial em Streamlit, publicado via túnel)

Antes de começar, configure os segredos no Colab (ícone de chave 🔑 na barra
lateral esquerda):
  - GROQ_API_KEY   — obrigatório, chave da API da Groq.
  - GITHUB_TOKEN   — opcional, Personal Access Token do GitHub (escopo
    `repo`) com leitura em laismngueira/minicurso-smc. Com ele, o início do
    Bloco II clona o repositório sozinho e copia os arquivos de apoio
    (Modelo_AI_v1.h5, DadosTratados.xlsx, os 3 PDFs, scp01_core.py) para
    /content/.

Sem GITHUB_TOKEN, envie manualmente pela aba de arquivos do Colab
(/content/) os mesmos arquivos, disponíveis em versao_colab/ neste
repositório:
  - Modelo_AI_v1.h5           (RNA já treinada)
  - DadosTratados.xlsx        (dados reais de campo, usados como contexto fixo)
  - 01_sistema_distribuicao.pdf, 02_sistema_controle.pdf, 03_dados.pdf
    (base de conhecimento do RAG)
  - scp01_core.py             (código da planta, PID, RAG e agente — os
    Blocos II-IV e a interface do Bloco V importam tudo daqui, em vez de
    cada um reescrever a mesma lógica)
  - app_streamlit.py          (cópia pronta da interface — opcional: o
    Bloco V já grava esse mesmo arquivo sozinho via `%%writefile`, então só
    é necessário enviá-lo manualmente se preferir pular essa célula)
"""

# ============================================================================
# Bloco I — Fundamentos da LLM
# ============================================================================
"""
## Bloco I — Fundamentos da LLM

Toda a parte "inteligente" do sistema (entender uma pergunta em português,
decidir o que fazer, explicar um resultado) é feita por uma LLM (Large
Language Model) hospedada na Groq — um provedor que roda modelos abertos
com inferência muito rápida.

Aqui só validamos a conexão: mandamos uma pergunta simples e conferimos que
a resposta chega.
"""

!pip install -q langchain langchain-groq langgraph

from langchain_groq import ChatGroq
from google.colab import userdata

GROQ_API_KEY = userdata.get('GROQ_API_KEY')

llm = ChatGroq(
    # "llama-3.3-70b-versatile" (usado nas primeiras versões deste minicurso)
    # foi descontinuado pela Groq e não está mais no catálogo — testado em
    # 31/08/2026 (`curl https://api.groq.com/openai/v1/models`). Substituído
    # por um modelo equivalente ainda disponível.
    model="openai/gpt-oss-120b",
    temperature=0.1,
    api_key=GROQ_API_KEY,
)

resp_test = llm.invoke("como funciona o controlador PID em uma planta industrial?")
print(resp_test.content)


# ============================================================================
# Bloco II — Sistema de Controle (planta RNA + PID)
# ============================================================================
"""
## Bloco II — Sistema de Controle

### A planta: uma RNA treinada com dados reais

A "planta" deste minicurso não é uma fórmula matemática — é uma **Rede
Neural Artificial (RNA)** treinada com dados reais de campo de um sistema de
distribuição de água (bomba centrífuga + inversor de frequência + rede
hidráulica). Ela recebe a frequência do inversor (a variável que o PID
manipula) e devolve a pressão prevista na rede (PT_4A). Para o PID, ela é só
uma caixa-preta: entra um sinal de controle, sai uma medição — o que
acontece por dentro (as 3 camadas da rede) não importa aqui.

Como as demais variáveis medidas (outras pressões e vazões da planta) também
influenciam a leitura de pressão e não são controladas por nós, usamos uma
linha real do conjunto de dados como "estado_base" fixo — só a coluna do
inversor é alterada pelo controlador.

### O controlador: PID em forma paralela

Usamos a forma paralela do PID (ganhos Kp, Ki, Kd diretos — sem passar por
constantes de tempo Ti/Td):

    saida = Kp*erro + Ki*integral + Kd*derivada

E aplicamos essa saída de forma **incremental** sobre o próprio sinal de
controle anterior (`u += saida`, com saturação) — é assim que a planta real
é operada: o inversor não "salta" para um novo valor absoluto a cada
amostra, ele é ajustado a partir do valor em que já está.

Os ganhos padrão (Kp=1, Ki=0.1, Kd=0.05) e o cenário de teste (setpoint
5.0 → 6.0 → 4.0, a cada 400 amostras, com passo de amostragem de 1s) foram
validados manualmente e reproduzem o comportamento documentado no projeto de
referência (PID_Aut_Inteligente).
"""

"""
### Baixando os arquivos de apoio (RNA, dataset, PDFs)

Em vez de enviar manualmente Modelo_AI_v1.h5, DadosTratados.xlsx e os PDFs
pela aba de arquivos toda vez que abrir uma sessão nova (o `/content/` do
Colab é apagado quando a sessão desconecta), esta célula clona o repositório
do GitHub e copia tudo de uma vez.

Requisito: configure um segredo `GITHUB_TOKEN` no Colab (ícone de chave 🔑
na barra lateral esquerda) com um Personal Access Token do GitHub (escopo
`repo`, já que este é um repositório privado — gere um em
https://github.com/settings/tokens, de preferência um *fine-grained token*
com acesso restrito só a este repositório). Se o segredo não estiver
configurado, a célula avisa e você pode enviar os arquivos manualmente como
alternativa.
"""

from pathlib import Path

from google.colab import userdata

try:
    GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')
except Exception:
    GITHUB_TOKEN = None

REPO_DIR = Path("/content/minicurso-smc")
ARQUIVOS_APOIO = [
    "Modelo_AI_v1.h5", "DadosTratados.xlsx",
    "01_sistema_distribuicao.pdf", "02_sistema_controle.pdf", "03_dados.pdf",
    "scp01_core.py",
]

if GITHUB_TOKEN and not REPO_DIR.exists():
    import os
    os.environ["GITHUB_TOKEN"] = GITHUB_TOKEN
    !git clone -q https://x-access-token:$GITHUB_TOKEN@github.com/laismngueira/minicurso-smc.git {REPO_DIR}
    origem = REPO_DIR / "versao_colab"
    for nome in ARQUIVOS_APOIO:
        !cp "{origem / nome}" /content/
    print("Arquivos de apoio copiados de", origem, "para /content/:")
    !ls -la /content/*.h5 /content/*.xlsx /content/*.pdf /content/scp01_core.py
elif GITHUB_TOKEN:
    print("Repositório já clonado em", REPO_DIR, "— nada a fazer.")
else:
    print(
        "Segredo GITHUB_TOKEN não configurado. Envie manualmente pela aba de "
        "arquivos do Colab: " + ", ".join(ARQUIVOS_APOIO)
    )

# scp01_core.py precisa ser importável (Blocos II-IV e a interface do
# Bloco V importam dele) — garante que /content/ está no sys.path, mesmo
# que o diretório de trabalho da sessão não seja exatamente /content/.
import sys

if "/content" not in sys.path:
    sys.path.insert(0, "/content")

!pip install -q sentence-transformers langchain_community

# Aquecimento "silencioso" do PyTorch, ANTES de importar o TensorFlow: as
# duas bibliotecas usam runtimes nativos (OpenMP/MKL) que entram em conflito
# (segfault) se carregadas na ordem errada no mesmo processo — e um simples
# `import torch` não basta, é preciso inicializar de verdade um modelo (o
# Bloco III usa exatamente este `HuggingFaceEmbeddings` para o RAG). Isso
# não tem relação com a planta em si; é só uma particularidade do ambiente,
# então plugamos aqui antes de tocar no TensorFlow.
from langchain_community.embeddings import HuggingFaceEmbeddings

_aquecimento_pytorch = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
_aquecimento_pytorch.embed_query("aquecimento")
del _aquecimento_pytorch

!pip install -q tensorflow scikit-learn pandas openpyxl matplotlib

"""
### O código da planta e do PID

Em vez de reescrever esse código aqui, ele já está pronto em
`scp01_core.py` (baixado pela célula de download acima) — o mesmo arquivo
que a interface do Bloco V também importa, então a lógica só existe escrita
uma vez. Aqui só importamos e testamos.
"""

from scp01_core import (
    buscar_melhores_parametros,
    carregar_planta_rna,
    planta_caixa_preta,
    simular_com_protecao_overshoot,
    simular_planta,
)

modelo, scaler, estado_base = carregar_planta_rna()
if modelo is None:
    raise FileNotFoundError(
        "Modelo_AI_v1.h5 / DadosTratados.xlsx não encontrados em /content/. "
        "Rode a célula de download no início deste bloco (ou envie os "
        "arquivos manualmente) antes de continuar."
    )

"""
### Testando a planta isoladamente

Antes de fechar a malha, vale ver como a RNA responde a diferentes valores
de frequência do inversor — isso ajuda a entender por que os ganhos do PID
precisam ser pequenos: a curva da planta não é linear, e em algumas faixas
(acima de ~50Hz) o ganho (variação de pressão por Hz) é bem mais alto.
"""

print("Curva estática da planta (u -> pressão prevista):")
for u_teste in [0, 20, 40, 50, 60, 80, 100]:
    y_teste = planta_caixa_preta(u_teste, modelo, scaler, estado_base)
    print(f"  u={u_teste:5.1f} Hz  ->  y={y_teste:.3f}")

"""
### Fechando a malha: simulação com o PID

`simular_planta` (em scp01_core.py) roda o laço fechado por `N_amostras`
passos, aplicando o PID incremental a cada amostra e registrando a
resposta. Ao final, calcula métricas clássicas de desempenho (overshoot,
tempo de acomodação, erro final, ISE, IAE, ITAE) e devolve tudo num
dicionário — inclusive o gráfico, já pronto em base64.
"""

from base64 import b64decode

from IPython.display import Image, display

resultados = simular_planta()
display(Image(b64decode(resultados["grafico"])))

"""### Resultados no cenário padrão (Kp=1, Ki=0.1, Kd=0.05)"""

print("\n" + "=" * 30)
print("  RESULTADOS DO CONTROLE PID")
print("=" * 30)
for chave, valor in resultados.items():
    if chave != "grafico":
        print(f"{chave:15}: {valor}")
print("=" * 30)

"""
### Otimização automática dos ganhos

`buscar_melhores_parametros` (em scp01_core.py) faz uma busca em grade
(grid search) — testa várias combinações de Kp/Ki/Kd e fica com a que
minimiza `ISE + 2*overshoot` (a penalidade em overshoot evita escolher
ganhos agressivos demais só porque reduzem o erro acumulado). Cada
simulação chama a RNA de verdade 1200 vezes, então essa busca é bem mais
lenta que uma simulação única — a grade já vem reduzida (4×4×3 = 48
combinações) para caber em poucos minutos.
"""

# Descomente para rodar a otimização (leva alguns minutos):
# melhor_resultado = buscar_melhores_parametros()
# print(melhor_resultado)


# ============================================================================
# Bloco III — Consulta ao RAG
# ============================================================================
"""
## Bloco III — Consulta ao RAG (Retrieval-Augmented Generation)

Para perguntas de **teoria** (o que é overshoot? qual o papel do termo
derivativo?), não queremos que a LLM "invente" uma resposta genérica —
queremos que ela responda com base em documentos técnicos reais.

O RAG faz isso em 4 passos:
  1. Lê todos os PDFs de `/content/`.
  2. Quebra cada PDF em pedaços pequenos (chunks), com uma leve sobreposição
     entre eles para não perder contexto nas bordas.
  3. Transforma cada chunk em um vetor numérico (embedding) e indexa tudo
     num banco vetorial (FAISS).
  4. Na hora da pergunta, busca os chunks mais parecidos com a pergunta e
     manda só esses trechos (não o PDF inteiro) para a LLM responder.
"""

!pip install -q --upgrade langchain langchain_community faiss-cpu langchain-text-splitters pymupdf sentence-transformers

"""
### O código do RAG

Assim como a planta, o código do RAG (carregar PDFs de `/content/`, dividir
em chunks, indexar em FAISS, responder com citações) já está pronto em
`scp01_core.py` — importamos e testamos aqui, sem reescrever nada.
"""

from scp01_core import build_retriever, perguntar_controle_rag

retriever, n_paginas, n_chunks, arquivos_pdf = build_retriever(llm)
print(f"Arquivos carregados: {arquivos_pdf}")
print(f"Total de páginas carregadas: {n_paginas}")
print(f"Total de chunks gerados: {n_chunks}")

"""### Testando o RAG"""

testes_rag = [
    "O que é overshoot em sistemas de controle em malha fechada?",
    "Qual é o papel do termo derivativo em um controlador PID?",
    "O que é o método Zero Order Hold (ZOH) e por que ele é usado na discretização da planta?",
]

for msg_teste in testes_rag:
    resposta = perguntar_controle_rag(msg_teste, llm, retriever)
    print("-" * 40)
    print(f"PERGUNTA: {msg_teste}")
    print(f"RESPOSTA: {resposta['answer']}")
    if resposta["contexto_encontrado"]:
        print("CITAÇÕES:")
        for c in resposta["citacoes"]:
            print(f" - {c['documento']}, pág. {c['pagina']}")


# ============================================================================
# Bloco IV — Agente de IA (LangGraph)
# ============================================================================
"""
## Bloco IV — Agente de IA

Até aqui temos três "ferramentas" separadas: o simulador de PID (Bloco II),
o RAG de teoria (Bloco III), e a LLM crua (Bloco I). O agente é a peça que
decide sozinha **qual** ferramenta usar, a partir de uma única pergunta em
linguagem natural.

O grafo de estados (LangGraph) funciona assim:

    START -> triagem -> [decide]
                          |-- TEORIA   -> teoria (RAG)     -> llm -> END
                          |-- SIMULAR  -> simular           -> resposta_final -> llm -> END
                          |-- OTIMIZAR -> otimizar           -> resposta_final -> llm -> END

O nó `triagem` usa a LLM com **saída estruturada** (um schema Pydantic) para
classificar a pergunta e já extrair, se houver, os valores de Kp/Ki/Kd
mencionados pelo usuário. O nó `llm`, no final, reescreve a resposta de
forma didática — mas com uma regra importante: se a pergunta era sobre
simular/otimizar, ele **não** pode reabrir uma aula de teoria sobre PID, só
reportar os números obtidos.
"""

!pip install -q --upgrade langgraph

"""
### O código do agente

O grafo de estados completo — nós de triagem, teoria (RAG), simular,
otimizar, resposta final e llm, junto com o schema `TriagemOut` usado na
triagem estruturada — já está pronto em `scp01_core.py`, montado sobre as
mesmas funções de planta e RAG dos Blocos II e III. Aqui só importamos,
construímos o grafo e testamos.
"""

from scp01_core import TRIAGEM_PROMPT, TriagemOut, build_workflow

app = build_workflow(llm, retriever)

"""### Testando só a triagem (antes de olhar o grafo completo)"""

from langchain_core.messages import HumanMessage, SystemMessage

# method="json_mode" evita um bug do Groq com modelos "reasoning/tool"
# (ex.: openai/gpt-oss-120b) em que o function-calling forçado do modo
# padrão gera uma chamada de ferramenta sintética "json" inexistente
# (BadRequestError: tool call validation failed). O prompt já descreve
# o formato JSON esperado, então json_mode funciona sem mudanças nele.
triagem_chain = llm.with_structured_output(TriagemOut, method="json_mode")

testes = [
    "o que é overshoot em sistemas de controle?",
    "simule a planta com kp=1.5 ki=0.1 kd=0.05",
    "otimize os parâmetros do PID para minimizar erro",
]

for msg_teste in testes:
    saida = triagem_chain.invoke([
        SystemMessage(content=TRIAGEM_PROMPT),
        HumanMessage(content=msg_teste),
    ])
    print(f"Pergunta: {msg_teste}\n -> Resposta: {saida.model_dump()}\n")

"""### Fluxograma do agente"""

from IPython.display import Image, display

graph_bytes = app.get_graph().draw_mermaid_png()
display(Image(graph_bytes))

"""### Testando o agente completo"""

pergunta = "simule a planta com kp=1 ki=0.1 kd=0.05"

resultado = app.invoke({"pergunta": pergunta}, config={"recursion_limit": 10})

print("\n" + "=" * 30)
print("RESPOSTA DO SISTEMA")
print("=" * 30 + "\n")
print(resultado["resposta"])


# ============================================================================
# Bloco V — Interface (painel industrial em Streamlit)
# ============================================================================
"""
## Bloco V — Interface

`app_streamlit.py` **importa** a mesma lógica de `scp01_core.py` que os
Blocos II-IV já usaram — nada da planta, do PID, do RAG ou do agente é
reescrito aqui. Este arquivo só acrescenta por cima: layout, CSS de estilo
SCADA/HMI, estado de sessão do chat e finas camadas de cache
(`st.cache_resource`/`st.cache_data`) sobre as mesmas funções.

`scp01_core.py` já está em `/content/` desde a célula de download no início
do Bloco II — só falta gravar `app_streamlit.py`. Rode a célula abaixo,
depois siga para a próxima seção para instalar as dependências da interface
e publicar o painel.
"""

# %%writefile app_streamlit.py
# -*- coding: utf-8 -*-
"""
SCP-01 — Painel Industrial de Controle PID
============================================

Interface Streamlit para o assistente de engenharia de controle do minicurso.
Mantém a planta e o agente originais (LLM de triagem + RAG sobre PDFs +
LangGraph), apenas trocando a interface Gradio por um painel de estilo
SCADA/HMI.

Toda a lógica de negócio (planta RNA, PID, RAG, agente LangGraph) vive em
`scp01_core.py` — este arquivo só cuida de layout, CSS, estado de sessão e
finas camadas de cache (`st.cache_resource`/`st.cache_data`) por cima das
funções de carregamento caras definidas lá.

Planta: RNA (Modelo_AI_v1.h5) treinada com dados reais de campo de um
sistema de distribuição de água (PID_Aut_Inteligente) — recebe a frequência
do inversor e devolve a pressão prevista (PT_4A). Depende de
Modelo_AI_v1.h5 e DadosTratados.xlsx estarem acessíveis (mesma pasta dos
PDFs). PID em forma paralela (Kp, Ki, Kd diretos, sem Ti/Td) igual à classe
PID de PID_Aut_Inteligente/notebook.ipynb — ganhos padrão Kp=1, Ki=0.1,
Kd=0.05 @ Ts=1s (1200 amostras, degraus de 400) reproduzem as Figuras
7-10 de PID_Aut_Inteligente/UFPB (1).pdf ("Kd=5" na legenda da Figura 7 é
um erro de digitação do relatório — confirmado rodando o código literal
do PDF: com Kd=5 o segundo degrau oscila (não bate com a figura), com
Kd=0.05 fica suave e o overshoot do primeiro degrau bate 16.4% ≈ os 16.6%
medidos na imagem).

Como rodar (Colab, com proxy nativo):
  1) Envie este arquivo, scp01_core.py, os PDFs de conhecimento e os
     arquivos da RNA (Modelo_AI_v1.h5, DadosTratados.xlsx) para a sessão do
     Colab (aba de arquivos, /content/).
  2) Rode o notebook de lançamento (colab_launch_streamlit.py) célula a
     célula.

Como rodar localmente:
  export GROQ_API_KEY=...
  streamlit run app_streamlit.py
"""

import base64
import os
from datetime import datetime
from typing import Dict, List, Optional

import streamlit as st
from dotenv import load_dotenv

import scp01_core as core

load_dotenv()

# ============================================================================
# Configuração da página e paleta industrial
# ============================================================================

st.set_page_config(
    page_title="SCP-01 · Controle PID",
    page_icon="🏭",
    layout="wide",
    initial_sidebar_state="expanded",
)

COR = core.COR

CSS = f"""
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600;700&family=Inter:wght@400;600;700&display=swap" rel="stylesheet">
<style>
:root {{ color-scheme: dark; }}

html, body, [data-testid="stAppViewContainer"], [data-testid="stHeader"] {{
    background-color: {COR["pagina"]} !important;
    color: {COR["texto"]};
    font-family: 'Inter', sans-serif;
}}

[data-testid="stSidebar"] {{
    background-color: {COR["painel"]};
    border-right: 1px solid {COR["borda"]};
}}

.scp-banner {{
    background: linear-gradient(180deg, {COR["painel_alt"]} 0%, {COR["painel"]} 100%);
    border: 1px solid {COR["borda"]};
    border-left: 4px solid {COR["serie_medida"]};
    border-radius: 6px;
    padding: 14px 20px;
    margin-bottom: 18px;
    display: flex;
    align-items: center;
    justify-content: space-between;
}}
.scp-banner h1 {{
    font-family: 'JetBrains Mono', monospace;
    font-size: 1.35rem;
    letter-spacing: 0.04em;
    margin: 0;
    color: {COR["texto"]};
}}
.scp-banner p {{
    margin: 2px 0 0 0;
    color: {COR["texto_mudo"]};
    font-size: 0.82rem;
    letter-spacing: 0.03em;
    text-transform: uppercase;
}}

.led {{
    display: inline-flex;
    align-items: center;
    gap: 6px;
    font-family: 'JetBrains Mono', monospace;
    font-size: 0.78rem;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    color: {COR["texto_sec"]};
    padding: 4px 10px;
    border: 1px solid {COR["borda"]};
    border-radius: 999px;
    background: {COR["painel_alt"]};
}}
.led .dot {{
    width: 8px; height: 8px; border-radius: 50%;
    box-shadow: 0 0 6px currentColor;
}}
.led.on .dot {{ background: {COR["bom"]}; color: {COR["bom"]}; }}
.led.off .dot {{ background: {COR["critico"]}; color: {COR["critico"]}; }}
.led.warn .dot {{ background: {COR["alerta"]}; color: {COR["alerta"]}; }}

.scp-panel {{
    background: {COR["painel"]};
    border: 1px solid {COR["borda"]};
    border-radius: 6px;
    padding: 16px 18px;
    margin-bottom: 14px;
}}

.scp-section-title {{
    font-family: 'JetBrains Mono', monospace;
    font-size: 0.82rem;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: {COR["texto_sec"]};
    border-bottom: 1px solid {COR["borda"]};
    padding-bottom: 6px;
    margin: 18px 0 12px 0;
}}

[data-testid="stChatMessage"] [data-testid="stMarkdownContainer"],
[data-testid="stChatMessage"] [data-testid="stMarkdownContainer"] * {{
    color: {COR["texto"]} !important;
}}

.scp-console {{
    background: #0a0a0a;
    border: 1px solid {COR["borda"]};
    border-radius: 6px;
    padding: 14px 16px;
    font-family: 'JetBrains Mono', monospace;
    font-size: 0.86rem;
    color: {COR["texto_sec"]};
    white-space: pre-wrap;
    max-height: 420px;
    overflow-y: auto;
}}

.scp-tile {{
    background: {COR["painel"]};
    border: 1px solid {COR["borda"]};
    border-radius: 6px;
    padding: 12px 14px;
    text-align: left;
}}
.scp-tile .label {{
    font-size: 0.72rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: {COR["texto_mudo"]};
    margin-bottom: 4px;
}}
.scp-tile .value {{
    font-family: 'JetBrains Mono', monospace;
    font-size: 1.5rem;
    font-weight: 600;
    color: {COR["texto"]};
}}
.scp-tile .unit {{
    font-size: 0.85rem;
    color: {COR["texto_mudo"]};
    margin-left: 4px;
}}
.scp-tile .badge {{
    display: inline-block;
    margin-top: 6px;
    font-size: 0.7rem;
    font-weight: 600;
    letter-spacing: 0.04em;
    text-transform: uppercase;
    padding: 2px 8px;
    border-radius: 999px;
}}

.scp-cite {{
    border-left: 3px solid {COR["serie_medida"]};
    background: {COR["painel_alt"]};
    padding: 8px 12px;
    margin-bottom: 8px;
    border-radius: 0 4px 4px 0;
    font-size: 0.85rem;
}}
.scp-cite .fonte {{
    font-family: 'JetBrains Mono', monospace;
    color: {COR["texto_mudo"]};
    font-size: 0.75rem;
    text-transform: uppercase;
}}

[data-testid="stChatInputTextArea"] {{
    color: #0b0b0b !important;
    caret-color: #0b0b0b;
}}
[data-testid="stChatInputTextArea"]::placeholder {{
    color: #52514e !important;
}}

.stButton > button {{
    font-family: 'JetBrains Mono', monospace;
    font-weight: 700;
    letter-spacing: 0.05em;
    text-transform: uppercase;
    border-radius: 4px;
    border: 1px solid {COR["borda"]};
}}
.stButton > button[kind="primary"] {{
    background: {COR["serie_medida"]};
    border-color: {COR["serie_medida"]};
}}

.scp-footer {{
    color: {COR["texto_mudo"]};
    font-family: 'JetBrains Mono', monospace;
    font-size: 0.72rem;
    text-align: right;
    margin-top: 24px;
    border-top: 1px solid {COR["borda"]};
    padding-top: 8px;
}}
</style>
"""
st.html(CSS)


def led(texto: str, estado: str) -> str:
    """estado: 'on' | 'off' | 'warn'"""
    return f'<span class="led {estado}"><span class="dot"></span>{texto}</span>'


def metric_tile(label: str, value, unit: str = "", status: Optional[str] = None, status_label: str = "") -> str:
    cor_badge = {
        "bom": COR["bom"],
        "alerta": COR["alerta"],
        "critico": COR["critico"],
    }.get(status)
    badge_html = ""
    if status and cor_badge:
        badge_html = (
            f'<div class="badge" style="background:{cor_badge}22;color:{cor_badge};'
            f'border:1px solid {cor_badge}66;">{status_label}</div>'
        )
    return f"""
    <div class="scp-tile">
        <div class="label">{label}</div>
        <div><span class="value">{value}</span><span class="unit">{unit}</span></div>
        {badge_html}
    </div>
    """


# ============================================================================
# Credenciais (Colab ou ambiente local) + camadas de cache do Streamlit
# sobre as funções caras definidas em scp01_core
# ============================================================================

def _get_groq_key() -> Optional[str]:
    if hasattr(st, "secrets"):
        try:
            chave = st.secrets.get("GROQ_API_KEY")
            if chave:
                return chave
        except Exception:
            pass
    return core.resolve_groq_key()


GROQ_API_KEY = _get_groq_key()


@st.cache_resource(show_spinner=False)
def get_llm():
    return core.get_llm(GROQ_API_KEY)


@st.cache_resource(show_spinner=False)
def build_retriever(_llm):
    return core.build_retriever(_llm)


@st.cache_resource(show_spinner=False)
def build_workflow(_llm, _retriever):
    return core.build_workflow(_llm, _retriever)


@st.cache_data(show_spinner=False)
def render_diagrama_destacado(_app, classificacao: Optional[str]) -> Optional[bytes]:
    return core.render_diagrama_destacado(_app, classificacao)


# ============================================================================
# Estado da sessão
# ============================================================================

if "resultado" not in st.session_state:
    st.session_state.resultado = None
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []
if "ultima_classificacao" not in st.session_state:
    st.session_state.ultima_classificacao = None

llm = get_llm()
retriever, n_paginas, n_chunks, arquivos_pdf = (None, 0, 0, [])
if llm is not None:
    retriever, n_paginas, n_chunks, arquivos_pdf = build_retriever(llm)

app_workflow = build_workflow(llm, retriever) if llm is not None else None

# Carregado depois do RAG (torch) de propósito — ver nota em
# core.carregar_planta_rna() sobre a ordem TF/PyTorch.
_modelo_rna, _, _ = core.carregar_planta_rna()
rna_disponivel = _modelo_rna is not None

# Cenário padrão: roda uma simulação com os ganhos de referência assim que
# o app abre, antes de qualquer pergunta do usuário, para o painel (Métricas
# / Tendência / Workflow) já vir populado em vez de "nenhuma simulação
# executada ainda". Só roda uma vez por sessão (resultado fica em cache no
# session_state depois disso).
if st.session_state.resultado is None and rna_disponivel:
    try:
        with st.spinner("CARREGANDO CENÁRIO PADRÃO..."):
            st.session_state.resultado = core.simular_planta(plot=True)
    except Exception:
        pass

# ============================================================================
# Cabeçalho (banner HMI)
# ============================================================================

status_geral = "on" if llm is not None else "off"
st.markdown(f"""
<div class="scp-banner">
    <div>
        <h1>SCP-01 · SISTEMA DE CONTROLE PID — MALHA FECHADA</h1>
        <p>Planta: RNA treinada com dados de campo (PT_4A) · sistema de distribuição de água</p>
    </div>
    <div>{led("SISTEMA " + ("ONLINE" if llm is not None else "OFFLINE"), status_geral)}</div>
</div>
""", unsafe_allow_html=True)

# ============================================================================
# Sidebar — Painel de controle
# ============================================================================

with st.sidebar:
    st.markdown("### 🏭 PAINEL DE CONTROLE")

    st.markdown(led("LLM (Groq)", "on" if llm is not None else "off"), unsafe_allow_html=True)
    st.markdown(
        led(f"RAG · {n_paginas} pág / {n_chunks} chunks" if retriever else "RAG · sem PDFs",
            "on" if retriever else "warn"),
        unsafe_allow_html=True,
    )
    st.markdown(led("Workflow", "on" if app_workflow is not None else "off"), unsafe_allow_html=True)
    st.markdown(
        led("RNA · modelo carregado" if rna_disponivel else "RNA · arquivos ausentes",
            "on" if rna_disponivel else "off"),
        unsafe_allow_html=True,
    )
    if not rna_disponivel:
        st.error("Modelo_AI_v1.h5 / DadosTratados.xlsx não encontrados. Envie os "
                 "arquivos para a sessão (mesma pasta dos PDFs) antes de simular.")

    if llm is None:
        st.error("GROQ_API_KEY não configurada. Defina em Colab (userdata), "
                 "st.secrets ou variável de ambiente.")

    st.divider()

    modo = st.radio(
        "MODO DE OPERAÇÃO",
        ["🤖 Assistente (IA)", "🎛️ Manual (Operador)"],
        label_visibility="visible",
    )

    st.divider()

    if modo == "🤖 Assistente (IA)":
        st.caption("Digite sua pergunta ou comando no chat, na aba **📟 Console** "
                   "→ campo na parte de baixo da tela.")
        if st.button("🗑️ Limpar conversa", use_container_width=True):
            st.session_state.chat_history = []
            st.rerun()
    else:
        st.markdown("**PARÂMETROS DO CONTROLADOR**")
        # Padrão = Figuras 7-10 de PID_Aut_Inteligente/UFPB (1).pdf
        # (classe PID: Kp=1, Ki=0.1, Kd=0.05).
        kp_manual = st.slider("Kp", 0.0, 50.0, 1.0, 0.1)
        ki_manual = st.slider("Ki", 0.0, 1.0, 0.1, 0.01)
        kd_manual = st.slider("Kd", 0.0, 1.0, 0.05, 0.01)
        col_a, col_b = st.columns(2)
        simular_manual = col_a.button("▶ SIMULAR", type="primary", use_container_width=True)
        otimizar_manual = col_b.button("🔍 OTIMIZAR", use_container_width=True)

    st.markdown(
        f'<div class="scp-footer">{datetime.now().strftime("%d/%m/%Y %H:%M:%S")}<br>'
        f'LangGraph · Groq GPT-OSS-120B</div>',
        unsafe_allow_html=True,
    )

# ============================================================================
# Execução (modo Manual — disparada pelos botões da sidebar)
# ============================================================================

if "erro_manual" not in st.session_state:
    st.session_state.erro_manual = None

if modo == "🎛️ Manual (Operador)" and simular_manual:
    st.session_state.erro_manual = None
    with st.spinner("SIMULANDO..."):
        try:
            st.session_state.resultado = core.simular_planta(kp_manual, ki_manual, kd_manual, plot=True)
        except Exception as e:
            st.session_state.erro_manual = str(e)

elif modo == "🎛️ Manual (Operador)" and otimizar_manual:
    st.session_state.erro_manual = None
    with st.spinner("BUSCANDO PARÂMETROS ÓTIMOS..."):
        try:
            st.session_state.resultado = core.buscar_melhores_parametros()
        except Exception as e:
            st.session_state.erro_manual = str(e)

if st.session_state.erro_manual:
    st.markdown(led(f"ALARME · {st.session_state.erro_manual}", "off"), unsafe_allow_html=True)

# ============================================================================
# Corpo principal — tudo em uma única tela (chat + painel de simulação)
# ============================================================================

def render_citacoes(citacoes: List[Dict]) -> None:
    if not citacoes:
        return
    st.markdown("**Citações técnicas:**")
    for c in citacoes:
        st.markdown(
            f'<div class="scp-cite"><div class="fonte">{c["documento"]} · pág. {c["pagina"]}</div>'
            f'{c["trecho"]}</div>',
            unsafe_allow_html=True,
        )


def status_overshoot(v: float):
    if v <= 10:
        return "bom", "OK"
    if v <= 30:
        return "alerta", "ATENÇÃO"
    return "critico", "CRÍTICO"


def status_erro(v_pct: float):
    """v_pct: erro final como % da referência — proporcional em vez de
    absoluto, já que a escala do setpoint muda conforme a planta (era ~1 na
    TF discretizada, é ~6-8 kPa na RNA)."""
    if v_pct <= 2:
        return "bom", "OK"
    if v_pct <= 10:
        return "alerta", "ATENÇÃO"
    return "critico", "CRÍTICO"


col_chat, col_painel = st.columns([3, 2], gap="large")

with col_chat:
    st.markdown(f'<div class="scp-section-title">💬 Assistente</div>', unsafe_allow_html=True)

    if not st.session_state.chat_history:
        st.markdown(
            '<div class="scp-console">Aguardando comando. Digite uma pergunta ou pedido no campo '
            'abaixo — ex.: "o que é overshoot?", "simule a planta com kp=1 ki=0.1 kd=0.05", '
            '"otimize os parâmetros".</div>',
            unsafe_allow_html=True,
        )

    for msg in st.session_state.chat_history:
        avatar = "🧑‍💻" if msg["role"] == "user" else "🏭"
        with st.chat_message(msg["role"], avatar=avatar):
            st.markdown(msg["content"])
            render_citacoes(msg.get("citacoes", []))

    pergunta_chat = st.chat_input(
        "Digite sua pergunta ou comando (ex.: simule a planta com kp=1 ki=0.1 kd=0.05)...",
        disabled=(llm is None),
    )

    if pergunta_chat:
        st.session_state.chat_history.append({"role": "user", "content": pergunta_chat})
        with st.chat_message("user", avatar="🧑‍💻"):
            st.markdown(pergunta_chat)

        with st.chat_message("assistant", avatar="🏭"):
            with st.spinner("PROCESSANDO..."):
                try:
                    resultado = app_workflow.invoke(
                        {"pergunta": pergunta_chat}, config={"recursion_limit": 10}
                    )
                    resposta = resultado.get("resposta") or "Sem resposta."
                    citacoes = resultado.get("citacoes", [])
                    if resultado.get("resultado"):
                        st.session_state.resultado = resultado["resultado"]
                    st.session_state.ultima_classificacao = resultado.get("classificacao")
                    st.markdown(resposta)
                    render_citacoes(citacoes)
                    st.session_state.chat_history.append(
                        {"role": "assistant", "content": resposta, "citacoes": citacoes}
                    )
                except Exception as e:
                    erro_msg = f"⚠️ ALARME · Falha na execução: {e}"
                    st.markdown(erro_msg)
                    st.session_state.chat_history.append({"role": "assistant", "content": erro_msg})

with col_painel:
    st.markdown(f'<div class="scp-section-title">📊 Métricas</div>', unsafe_allow_html=True)

    r = st.session_state.resultado
    if r and r.get("overshoot") is not None:
        s_over, l_over = status_overshoot(r["overshoot"])
        ref = r.get("referencia") or 1.0
        s_err, l_err = status_erro(abs(r["erro_final"]) / ref * 100)

        c1, c2 = st.columns(2)
        c1.markdown(metric_tile("Overshoot", f'{r["overshoot"]:.2f}', "%", s_over, l_over), unsafe_allow_html=True)
        c2.markdown(metric_tile("Erro final", f'{r["erro_final"]:.4f}', "", s_err, l_err), unsafe_allow_html=True)

        c3, c4 = st.columns(2)
        c3.markdown(metric_tile("Tempo de acomodação", f'{r["tempo_acomod"]:.2f}', "s"), unsafe_allow_html=True)
        c4.markdown(metric_tile("ISE", f'{r["ise"]:.2f}'), unsafe_allow_html=True)

        c5, c6 = st.columns(2)
        c5.markdown(metric_tile("IAE", f'{r["iae"]:.2f}'), unsafe_allow_html=True)
        c6.markdown(metric_tile("ITAE", f'{r["itae"]:.2f}'), unsafe_allow_html=True)

        st.markdown("<div style='height:6px'></div>", unsafe_allow_html=True)
        c7, c8, c9 = st.columns(3)
        c7.markdown(metric_tile("Kp", f'{r["Kp"]:.3f}'), unsafe_allow_html=True)
        c8.markdown(metric_tile("Ki", f'{r["Ki"]:.3f}'), unsafe_allow_html=True)
        c9.markdown(metric_tile("Kd", f'{r["Kd"]:.3f}'), unsafe_allow_html=True)
    else:
        st.info("Nenhuma simulação executada ainda.")

    st.markdown(f'<div class="scp-section-title">📈 Tendência</div>', unsafe_allow_html=True)
    if r and r.get("grafico"):
        img_bytes = base64.b64decode(r["grafico"])
        st.image(img_bytes, use_container_width=True)
    else:
        st.info("Nenhuma simulação executada ainda.")

    st.markdown(f'<div class="scp-section-title">🔀 Workflow</div>', unsafe_allow_html=True)
    if app_workflow is not None:
        rotulo_no = {
            "SIMULAR": "🔧 SIMULAR — nó `simular`",
            "OTIMIZAR": "🧠 OTIMIZAR — nó `otimizar`",
            "TEORIA": "📚 TEORIA — nó `teoria` (RAG)",
        }.get(st.session_state.ultima_classificacao, "— nenhuma execução via chat ainda —")

        st.markdown(
            f'<div style="margin-bottom:10px;">'
            f'<span style="color:{COR["texto_mudo"]};font-size:0.8rem;text-transform:uppercase;'
            f'letter-spacing:0.04em;">Último agente acionado</span><br>'
            f'<span style="font-family:\'JetBrains Mono\',monospace;font-size:1.1rem;'
            f'color:{COR["texto"]};">{rotulo_no}</span></div>',
            unsafe_allow_html=True,
        )

        diagrama = render_diagrama_destacado(app_workflow, st.session_state.ultima_classificacao)
        if diagrama:
            st.image(diagrama, use_container_width=True)
            st.markdown(
                f'<div style="font-size:0.78rem;color:{COR["texto_mudo"]};margin-top:8px;">'
                f'<span style="color:{COR["serie_medida"]};">●</span> nó executado nesta interação &nbsp;·&nbsp; '
                f'<span style="color:{COR["bom"]};">●</span> início / fim &nbsp;·&nbsp; '
                f'<span style="color:{COR["texto_mudo"]};">●</span> não utilizado</div>',
                unsafe_allow_html=True,
            )
        else:
            st.warning("Não foi possível renderizar o diagrama (sem acesso à internet?).")
    else:
        st.info("Workflow indisponível — configure a GROQ_API_KEY.")

"""
### Instalando dependências e publicando (proxy nativo do Colab)

Com `app_streamlit.py` já gravado em `/content/` (célula acima, ou enviado
manualmente pela aba de arquivos), instale as dependências da interface e
suba o painel.

Usamos o proxy de porta nativo do Colab (`google.colab.output`) em vez de
um túnel de terceiros (localtunnel/ngrok): não precisa de `npm install`,
não pede senha e não falha ao carregar os módulos JS do Streamlit (o
localtunnel é conhecido por ser instável nisso). Além disso,
`userdata.get()` só funciona dentro do kernel do notebook — como o
Streamlit sobe como um processo separado (`!streamlit run ... &`), a chave
precisa ser repassada via variável de ambiente ANTES de subir o processo,
senão o painel aparece como "SISTEMA OFFLINE" mesmo com o segredo
configurado.
"""

import os
import time

from google.colab import userdata

os.environ["GROQ_API_KEY"] = userdata.get("GROQ_API_KEY")

!pip install -q streamlit python-dotenv

!streamlit run /content/app_streamlit.py --server.port 8501 &>/content/logs_streamlit.txt &

time.sleep(8)  # dá tempo do Streamlit subir antes de abrir o proxy

from google.colab.output import eval_js

print(eval_js("google.colab.kernel.proxyPort(8501)"))

"""
### Solução de problemas

- Se a página não carregar: rode `!cat /content/logs_streamlit.txt` para
  ver o erro real do Streamlit, ou aumente o `time.sleep` acima e rode a
  célula de novo (o Streamlit pode levar mais que 8s para subir).
- Se o painel mostrar "SISTEMA OFFLINE": confirme que a célula acima
  rodou sem erro no `os.environ["GROQ_API_KEY"] = userdata.get(...)` — se
  o secret não estiver liberado para este notebook, essa linha lança
  exceção antes mesmo de chegar no Streamlit.
- Se o LED de RAG aparecer em amarelo ("sem PDFs"): confirme que os PDFs
  foram enviados para /content/ antes de rodar o Streamlit.
- Se o LED de RNA aparecer vermelho ("arquivos ausentes"): confirme que
  Modelo_AI_v1.h5 e DadosTratados.xlsx foram enviados para /content/.
- Se o processo do Streamlit cair sem erro visível (segfault): é conflito
  TensorFlow/PyTorch quando a ordem de import muda — dentro de
  app_streamlit.py o import do TensorFlow é local (dentro de
  `carregar_planta_rna()`), de propósito; não mova para o topo do arquivo.
"""
