# -*- coding: utf-8 -*-
"""Minicurso_SCP01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16iV6CQcMq5XZvxXIxzNkCdnYXMirR1ZP

===============================================================================
MINICURSO: Assistente de Controle PID com Agente de IA (LangGraph + Groq + RAG)
===============================================================================

Neste minicurso vamos construir, em 5 blocos, um assistente inteligente
capaz de ajustar um controlador PID em uma planta industrial real
(sistema de distribuição de água):

  Bloco I   — LLM básica (Groq): primeiro contato com o modelo de linguagem
  Bloco II  — Sistema de Controle: planta (RNA) + controlador PID
  Bloco III — RAG: a IA responde perguntas de teoria com base em PDFs
  Bloco IV  — Agente (LangGraph): a IA decide entre teoria, simular ou otimizar
  Bloco V   — Interface: painel interativo em Gradio

-------------------------------------------------------------------------------
Antes de começar
-------------------------------------------------------------------------------
No Colab, adicione o segredo (ícone de chave 🔑 na barra lateral esquerda):

  - GROQ_API_KEY  → chave da API da Groq (obrigatório)

Os arquivos de apoio (modelo treinado, dados e PDFs) são baixados
automaticamente no Bloco II — não é preciso enviar nada manualmente.

Ao final do notebook, o Bloco V abre um painel interativo com um link
público, gerado automaticamente pelo Gradio.

## Bloco I — Fundamentos da LLM
"""

!pip install -q langchain langchain-groq langgraph

from langchain_groq import ChatGroq
from google.colab import userdata

GROQ_API_KEY = userdata.get('GROQ_API_KEY')  # confira o nome do segredo no Colab

llm = ChatGroq(
    model="openai/gpt-oss-120b",
    temperature=0.1,  # 0 a 1: quanto maior, mais criativa a resposta
    api_key=GROQ_API_KEY,
)

resp_test = llm.invoke("como funciona o controlador PID em uma planta industrial?") # varie as perguntas
print(resp_test.content)

"""## Bloco II — Sistema de Controle

### A planta: uma RNA no lugar do sistema real

Em vez de usar a planta física, usamos uma Rede Neural Artificial (RNA)
treinada com dados de laboratório de um sistema de distribuição de água
(bomba centrífuga, inversor de frequência e rede hidráulica). Ela funciona
como uma caixa preta: recebe a frequência do inversor (o sinal que o PID
controla) e devolve a pressão prevista na rede, com base no que aprendeu
desses dados.

As outras variáveis do sistema (demais pressões e vazões) não são
controladas por nós, então mantemos elas fixas em um valor real de
referência (estado_base). Só a frequência do inversor muda a cada passo
do controlador.

### O controlador PID

    saida = Kp*erro + Ki*integral + Kd*derivada

O PID aqui é incremental: a cada passo, ele soma um ajuste ao sinal de
controle anterior (u += saida), em vez de calcular um valor absoluto novo.
É assim que a planta real também é operada.

Os ganhos padrão são Kp=1, Ki=0.1, Kd=0.05, testados com o setpoint
variando de 5.0 para 6.0 e depois para 4.0.

### Passo 1 — Baixando os arquivos de apoio (RNA, dataset, PDFs)

Como o repositório do GitHub é público, esta célula baixa automaticamente
os arquivos necessários (Modelo_AI_v1.h5, DadosTratados.xlsx e os PDFs) e
copia tudo para /content/. Assim não é preciso enviar nada manualmente pela
aba de arquivos, mesmo depois de reiniciar a sessão do Colab.
"""

from pathlib import Path

REPO_DIR = Path("/content/minicurso-smc")
ARQUIVOS_APOIO = [
    "Modelo_AI_v1.h5", "DadosTratados.xlsx",
    "01_sistema_distribuicao.pdf", "02_sistema_controle.pdf", "03_dados.pdf",
]

if not REPO_DIR.exists():
    !git clone -q https://github.com/laismngueira/minicurso-smc.git {REPO_DIR}
    origem = REPO_DIR / "versao_colab"
    for nome in ARQUIVOS_APOIO:
        !cp "{origem / nome}" /content/
    print("Arquivos de apoio copiados para /content/:")
    !ls -la /content/*.h5 /content/*.xlsx /content/*.pdf
else:
    print("Repositório já clonado em", REPO_DIR)

!pip install -q sentence-transformers langchain_community

# Inicializa o PyTorch antes do TensorFlow para evitar conflito entre as
# bibliotecas (erro comum quando as duas são carregadas na ordem errada).
from langchain_community.embeddings import HuggingFaceEmbeddings

_aquecimento_pytorch = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
_aquecimento_pytorch.embed_query("aquecimento")
del _aquecimento_pytorch

!pip install -q tensorflow scikit-learn pandas openpyxl matplotlib

import base64
import io
import warnings

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import load_model

warnings.filterwarnings("ignore", message="X does not have valid feature names")

def _localizar_arquivo(nome):
    encontrados = list(Path("/content/").glob(nome))
    if not encontrados:
        raise FileNotFoundError(
            f"Arquivo '{nome}' não encontrado em /content/. Rode a célula "
            "anterior para baixar os arquivos de apoio."
        )
    return encontrados[0]


modelo = load_model(_localizar_arquivo("Modelo_AI_v1.h5"))
dados = pd.read_excel(_localizar_arquivo("DadosTratados.xlsx"))

COLUNAS_ENTRADA = [
    "Inversor", "PT_1B", "PT_1C", "PT_1D", "PT_2A", "PT_2B",
    "PT_2C", "PT_3A", "PT_5A", "FT_1A", "FT_3A", "FT_4A", "FT_6A",
]
IDX_VARIAVEL_MANIPULADA = 0  # coluna Inversor: frequência, variável manipulada pelo PID
LIMITE_INF_U, LIMITE_SUP_U = 0.0, 100.0  # faixa operacional do inversor (Hz)

X = dados[COLUNAS_ENTRADA]

# scaler ajustado no dataset inteiro, mesma normalização usada no treino da RNA
scaler = StandardScaler()
scaler.fit(X)

estado_base = X.iloc[0].values.copy()

"""### Passo 2 — Testando a planta isoladamente

Antes de fechar a malha, vale ver como a RNA responde a diferentes valores
de frequência do inversor. Isso ajuda a entender por que os ganhos do PID
precisam ser pequenos: a curva da planta não é linear, e em algumas faixas
(acima de aproximadamente 50Hz) o ganho, ou seja a variação de pressão por
Hz, é bem mais alto.
"""

import warnings

warnings.filterwarnings("ignore", message="X does not have valid feature names")

# ---------------------------------------------------------------------------
# Curva estática da planta: calculada uma única vez, em lote, para depois
# ser reaproveitada por interpolação em vez de chamar a rede neural a cada
# passo de simulação.
# ---------------------------------------------------------------------------
_U_GRID = np.linspace(LIMITE_INF_U, LIMITE_SUP_U, 401)

_entradas_grid = np.tile(estado_base, (len(_U_GRID), 1))
_entradas_grid[:, IDX_VARIAVEL_MANIPULADA] = _U_GRID
_entradas_grid_escalada = scaler.transform(_entradas_grid).astype("float32")
_Y_GRID = modelo(_entradas_grid_escalada, training=False).numpy().flatten()


def planta_caixa_preta(u):
    """Caixa-preta: devolve a pressão prevista para o sinal de controle 'u'
    (frequência do inversor), por interpolação na curva estática já
    calculada em _U_GRID / _Y_GRID."""
    return float(np.interp(np.clip(u, LIMITE_INF_U, LIMITE_SUP_U), _U_GRID, _Y_GRID))


print("Curva estática da planta (u -> pressão prevista):")
for u_teste in [0, 20, 40, 50, 60, 80, 100]:
    print(f"  u={u_teste:5.1f} Hz  ->  y={planta_caixa_preta(u_teste):.3f}")
    warnings.filterwarnings("ignore", message="X does not have valid feature names")

"""### Passo 3 — Fechando a malha: simulação com o PID

A função simular_planta roda o laço fechado por N_amostras passos,
aplicando o PID incremental a cada amostra e registrando a resposta. Ao
final, ela calcula as métricas clássicas de desempenho (overshoot, tempo
de acomodação, erro final, ISE, IAE, ITAE) e devolve tudo em um único
resultado, já incluindo o gráfico pronto para ser exibido na interface.
"""

def simular_planta(
    Kp=1.0, Ki=0.1, Kd=0.05,
    T_amostragem=1.0, N_amostras=1200, plot=True,
    protecao_overshoot=False, overshoot_maximo=20.0, fator_reducao=0.7, tentativas_max=5,
):
    def _rodar(kp, ki, kd, plotar):
        segmento = N_amostras // 3
        yr = np.zeros(N_amostras)
        y_med = np.zeros(N_amostras)
        yr[0:segmento] = 5.0
        yr[segmento:2 * segmento] = 6.0
        yr[2 * segmento:3 * segmento] = 4.0

        y = np.zeros(N_amostras)
        u = np.zeros(N_amostras)
        erro = np.zeros(N_amostras)

        u_atual = float(estado_base[IDX_VARIAVEL_MANIPULADA])
        integral_acc = 0.0
        erro_anterior = 0.0

        for k in range(N_amostras):
            if k == segmento or k == 2 * segmento:
                integral_acc = 0.0
                erro_anterior = 0.0

            u[k] = u_atual
            y[k] = planta_caixa_preta(u_atual)
            y_med[k] = y[k]
            erro[k] = yr[k] - y_med[k]

            integral_acc += erro[k] * T_amostragem
            derivada = (erro[k] - erro_anterior) / T_amostragem
            erro_anterior = erro[k]
            controle = kp * erro[k] + ki * integral_acc + kd * derivada

            u_atual = np.clip(u_atual + controle, LIMITE_INF_U, LIMITE_SUP_U)

        tempo = np.arange(0, N_amostras) * T_amostragem

        ise = np.sum(erro**2) * T_amostragem
        iae = np.sum(np.abs(erro)) * T_amostragem
        itae = np.sum(tempo * np.abs(erro)) * T_amostragem

        y_segment = y_med[:segmento]
        ref = yr[0]
        overshoot = (np.max(y_segment) - ref) / ref * 100 if np.max(y_segment) > ref else 0
        erro_final = abs(ref - y_segment[-1])

        sup, inf = ref * 1.02, ref * 0.98
        indices_fora = np.where((y_segment < inf) | (y_segment > sup))[0]
        tempo_acomod = tempo[indices_fora[-1] + 1] if len(indices_fora) else tempo[0]

        img64 = None
        if plotar:
            fig, ax = plt.subplots(figsize=(9, 4))
            ax.plot(tempo, y, linewidth=1.2, label="Variável Controlada")
            ax.plot(tempo, yr, "--", linewidth=1.0, label="Setpoint")
            ax.set_title(f"PID | Kp={kp:.2f} Ki={ki:.2f} Kd={kd:.2f}")
            ax.set_xlabel("Tempo (s)")
            ax.set_ylabel("Amplitude")
            ax.grid(True)
            ax.legend()
            plt.show()

            buf = io.BytesIO()
            fig.savefig(buf, format="png")
            buf.seek(0)
            img64 = base64.b64encode(buf.getvalue()).decode("utf-8")
            plt.close(fig)

        return {
            "Kp": kp, "Ki": ki, "Kd": kd,
            "overshoot": round(overshoot, 2),
            "tempo_acomod": round(float(tempo_acomod), 2),
            "erro_final": round(erro_final, 4),
            "referencia": float(ref),
            "ise": round(ise, 2),
            "iae": round(iae, 2),
            "itae": round(itae, 2),
            "grafico": img64,
        }

    resultado = _rodar(Kp, Ki, Kd, plot)

    if not protecao_overshoot:
        return resultado

    kp_atual, ki_atual = Kp, Ki
    tentativa = 1
    while resultado["overshoot"] > overshoot_maximo and tentativa < tentativas_max:
        print(
            f"⚠️ Overshoot de {resultado['overshoot']}% acima do limite de "
            f"{overshoot_maximo}%. Reduzindo Kp e Ki (tentativa {tentativa}/{tentativas_max}).",
            flush=True,
        )
        kp_atual *= fator_reducao
        ki_atual *= fator_reducao
        resultado = _rodar(kp_atual, ki_atual, Kd, plot)
        tentativa += 1

    if tentativa >= tentativas_max and resultado["overshoot"] > overshoot_maximo:
        print(
            f"⚠️ Limite de tentativas atingido. Seguindo com overshoot de "
            f"{resultado['overshoot']}%.",
            flush=True,
        )

    return resultado


resultados = simular_planta()
warnings.filterwarnings("ignore", message="X does not have valid feature names")


print("\n" + "=" * 30)
print("  RESULTADOS DO CONTROLE PID")
print("=" * 30)
for chave, valor in resultados.items():
    if chave != "grafico":
        print(f"{chave:15}: {valor}")
print("=" * 30)

"""### Passo 4 — Otimização automática dos ganhos

A função buscar_melhores_parametros faz uma busca em grade (grid search):
testa várias combinações de Kp, Ki e Kd e fica com a que minimiza o
overshoot obtido na simulação.

Cada simulação chama a RNA 1200 vezes, então essa busca é bem mais lenta
que uma simulação única. Por isso a grade já foi reduzida para 48
combinações (4 valores de Kp, 4 de Ki e 3 de Kd), o suficiente para caber
em poucos minutos.
"""

import random
import time

def buscar_melhores_parametros(
    geracoes_sem_melhora_max=8,
    geracoes_valor_repetido_max=5,
    tolerancia=0.5,
    custo_alvo=None,
    seed=42,
):
    """
    geracoes_sem_melhora_max: número de gerações consecutivas sem melhora
    significativa antes de considerar convergido.

    geracoes_valor_repetido_max: número de gerações consecutivas em que o
    melhor custo se repete exatamente, um critério mais rígido que indica
    estabilização total.

    tolerancia: variação mínima de custo para contar como melhora real.

    custo_alvo: se definido, encerra assim que o melhor custo atingir esse
    valor, independente dos demais critérios.

    seed: embaralha a ordem das combinações para os critérios de
    convergência não serem enviesados pela ordem original da grade.
    """
    combinacoes = [
        (kp, ki, kd)
        for kp in np.linspace(0.2, 3.0, 4)
        for ki in np.linspace(0.02, 0.3, 4)
        for kd in np.linspace(0.0, 0.2, 3)
    ]
    random.Random(seed).shuffle(combinacoes)

    total = len(combinacoes)
    melhor, melhor_custo = None, 1e9
    geracoes_sem_melhora = 0
    geracoes_valor_repetido = 0
    custo_anterior = None
    inicio = time.time()

    print(
        f"🧠 Otimização iniciada. Até {total} combinações, com convergência em "
        f"{geracoes_sem_melhora_max} gerações sem melhora ou "
        f"{geracoes_valor_repetido_max} gerações com valor repetido.",
        flush=True,
    )

    for i, (kp, ki, kd) in enumerate(combinacoes, start=1):
        decorrido = time.time() - inicio
        print(
            f"  [{i:02d}/{total}] Kp={kp:.2f} Ki={ki:.2f} Kd={kd:.2f} "
            f"({decorrido:.1f}s, sem melhora há {geracoes_sem_melhora}, "
            f"valor repetido há {geracoes_valor_repetido})",
            flush=True,
        )
        try:
            r = simular_planta(kp, ki, kd, plot=False)
            custo = r["overshoot"]
            if np.isnan(custo) or np.isinf(custo):
                print("    Custo inválido (nan ou inf), pulando.", flush=True)
                geracoes_sem_melhora += 1
                continue

            # houve melhora significativa, fora da tolerância?
            if custo < melhor_custo - tolerancia:
                melhor_custo, melhor = custo, r
                geracoes_sem_melhora = 0
                print(f"    Novo melhor custo: {custo:.2f}.", flush=True)
            else:
                geracoes_sem_melhora += 1

            # o melhor custo se manteve exatamente igual ao da geração anterior?
            if custo_anterior is not None and round(melhor_custo, 6) == round(custo_anterior, 6):
                geracoes_valor_repetido += 1
            else:
                geracoes_valor_repetido = 0
            custo_anterior = melhor_custo

        except Exception as e:
            print(f"    Erro nesta combinação: {e}", flush=True)
            geracoes_sem_melhora += 1
            continue

        if custo_alvo is not None and melhor_custo <= custo_alvo:
            print(
                f"🎯 Meta de custo atingida ({melhor_custo:.2f} <= {custo_alvo}). "
                f"Parando em {i}/{total}.",
                flush=True,
            )
            break

        if geracoes_sem_melhora >= geracoes_sem_melhora_max:
            print(
                f"🛑 Convergência por estagnação: {geracoes_sem_melhora_max} gerações "
                f"seguidas sem melhora. Parando em {i}/{total}.",
                flush=True,
            )
            break

        if geracoes_valor_repetido >= geracoes_valor_repetido_max:
            print(
                f"🛑 Convergência por valor repetido: melhor custo estável há "
                f"{geracoes_valor_repetido_max} gerações. Parando em {i}/{total}.",
                flush=True,
            )
            break

    total_tempo = time.time() - inicio
    if melhor is None:
        print(f"🧠 Otimização concluída em {total_tempo:.1f}s. Nenhuma combinação válida encontrada.", flush=True)
        return None

    print(
        f"🧠 Otimização concluída em {total_tempo:.1f}s. Melhor combinação: "
        f"Kp={melhor['Kp']:.2f} Ki={melhor['Ki']:.2f} Kd={melhor['Kd']:.2f} "
        f"(custo={melhor_custo:.2f}).",
        flush=True,
    )
    return simular_planta(melhor["Kp"], melhor["Ki"], melhor["Kd"], plot=True)


# ---------------------------------------------------------------------------
# Célula de teste
# ---------------------------------------------------------------------------
print("=" * 60)
print("TESTE: otimização com critérios de convergência")
print("=" * 60)
t0 = time.time()
resultado_teste = buscar_melhores_parametros(
    geracoes_sem_melhora_max=8,
    geracoes_valor_repetido_max=5,
    tolerancia=0.5,
)
print(f"\nTempo total: {time.time() - t0:.1f}s")

"""## Bloco III — Consulta ao RAG (Retrieval-Augmented Generation)

Para perguntas de teoria, como o que é overshoot ou qual a função do termo
derivativo, a resposta não deve ser gerada livremente pela LLM. É necessário
que ela se baseie em documentos técnicos reais, evitando respostas genéricas
ou imprecisas.

O RAG realiza esse processo em quatro etapas:

  1. Leitura de todos os PDFs disponíveis em /content/.
  2. Divisão de cada documento em pequenos trechos (chunks), com uma leve
     sobreposição entre eles para preservar o contexto nas bordas.
  3. Conversão de cada trecho em um vetor numérico (embedding) e indexação
     desses vetores em um banco vetorial (FAISS).
  4. No momento da pergunta, busca dos trechos mais relevantes e envio
     apenas deles, e não do documento completo, para a LLM gerar a resposta.
"""

!pip install -q --upgrade langchain langchain_community faiss-cpu langchain-text-splitters pymupdf sentence-transformers

from pathlib import Path

from langchain_community.document_loaders import PyMuPDFLoader

docs = []
for n in Path("/content/").glob("*.pdf"):
    try:
        loader = PyMuPDFLoader(str(n))
        docs.extend(loader.load())
        print(f"Carregado com sucesso arquivo {n.name}")
    except Exception as e:
        print(f"Erro ao carregar arquivo {n.name}: {e}")

print(f"Total de páginas carregadas: {len(docs)}")

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(chunk_size=400, chunk_overlap=40)
chunks = splitter.split_documents(docs)
print(f"Total de chunks gerados: {len(chunks)}")

from langchain_community.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

from langchain_community.vectorstores import FAISS

vectorstore = FAISS.from_documents(chunks, embeddings)
retriever = vectorstore.as_retriever(
    search_type="similarity_score_threshold",
    search_kwargs={"score_threshold": 0.15, "k": 4},
)

from langchain_core.prompts import ChatPromptTemplate

prompt_rag = ChatPromptTemplate.from_messages([
    ("system",
     "Você é um assistente especialista em sistemas de controle em malha fechada "
     "aplicados a processos industriais.\n\n"
     "Seu conhecimento baseia-se em documentos técnicos sobre:\n"
     "- Controle PID\n- Métricas de desempenho (ISE, IAE, ITAE, overshoot)\n"
     "- Modelagem de plantas\n- Discretização de sistemas (ZOH)\n"
     "- Controle de pressão em sistemas de distribuição de água\n\n"
     "A saída do sistema corresponde à pressão da rede hidráulica.\n\n"
     "Responda SOMENTE com base no contexto fornecido.\n"
     "Se não houver informação suficiente no contexto, responda apenas: 'Não sei'."),
    ("human", "Pergunta: {input}\n\nContexto técnico:\n{context}"),
])

from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

document_chain = (
    {"context": lambda x: x["context"], "input": RunnablePassthrough()}
    | prompt_rag | llm | StrOutputParser()
)

import re


def _clean_text(s):
    return re.sub(r"\s+", " ", s or "").strip()


def extrair_trecho(texto, query, janela=240):
    txt = _clean_text(texto)
    termos = [t.lower() for t in re.findall(r"\w+", query or "") if len(t) >= 4]
    pos = -1
    for t in termos:
        pos = txt.lower().find(t)
        if pos != -1:
            break
    if pos == -1:
        pos = 0
    ini = max(0, pos - janela // 2)
    fim = min(len(txt), pos + janela // 2)
    return txt[ini:fim]


def formatar_citacoes(docs_rel, query):
    cites, seen = [], set()
    for d in docs_rel:
        src = Path(d.metadata.get("source", "")).name
        page = int(d.metadata.get("page", 0)) + 1
        key = (src, page)
        if key in seen:
            continue
        seen.add(key)
        cites.append({"documento": src, "pagina": page, "trecho": extrair_trecho(d.page_content, query)})
    return cites[:3]


def perguntar_controle_rag(pergunta):
    docs_relacionados = retriever.invoke(pergunta)
    if not docs_relacionados:
        return {"answer": "Não sei.", "citacoes": [], "contexto_encontrado": False}

    answer = document_chain.invoke({"input": pergunta, "context": docs_relacionados})
    txt = (answer or "").strip()

    if txt.rstrip(".!?") == "Não sei":
        return {"answer": "Não sei.", "citacoes": [], "contexto_encontrado": False}

    return {
        "answer": txt,
        "citacoes": formatar_citacoes(docs_relacionados, pergunta),
        "contexto_encontrado": True,
    }



testes_rag = [
    "O que é overshoot em sistemas de controle em malha fechada?",
    "Qual é o papel do termo derivativo em um controlador PID?",
    "O que é o método Zero Order Hold (ZOH) e por que ele é usado na discretização da planta?",
]

for msg_teste in testes_rag:
    resposta = perguntar_controle_rag(msg_teste)
    print("-" * 40)
    print(f"PERGUNTA: {msg_teste}")
    print(f"RESPOSTA: {resposta['answer']}")
    if resposta["contexto_encontrado"]:
        print("CITAÇÕES:")
        for c in resposta["citacoes"]:
            print(f" - {c['documento']}, pág. {c['pagina']}")

"""## Bloco IV — Agente de IA

Até aqui existem três ferramentas separadas: o simulador de PID (Bloco II),
o RAG de teoria (Bloco III) e a LLM básica (Bloco I). O agente é o
componente responsável por decidir, de forma autônoma, qual dessas
ferramentas utilizar a partir de uma única pergunta em linguagem natural.

O grafo de estados, construído com LangGraph, segue a seguinte estrutura:

    START -> triagem -> [decide]
                          |-- TEORIA   -> teoria (RAG) -> llm -> END
                          |-- SIMULAR  -> simular -> resposta_final -> llm -> END
                          |-- OTIMIZAR -> otimizar -> resposta_final -> llm -> END

O nó triagem utiliza a LLM com saída estruturada (um schema Pydantic) para
classificar a pergunta e extrair, quando presentes, os valores de Kp, Ki e
Kd mencionados pelo usuário. Já o nó llm é responsável por reescrever a
resposta final de forma didática, respeitando uma regra importante: quando
a pergunta envolve simulação ou otimização, ele deve apenas reportar os
resultados obtidos, sem reabrir uma explicação teórica sobre o PID.
"""

!pip install -q --upgrade langgraph

from typing import Dict, List, Literal, Optional, TypedDict

from langchain_core.messages import HumanMessage, SystemMessage
from langgraph.graph import END, START, StateGraph
from pydantic import BaseModel

TRIAGEM_PROMPT = (
    "Você é um agente de triagem para um assistente de engenharia de controle "
    "utilizado em uma planta industrial em malha fechada.\n\n"
    "O sistema possui três funcionalidades principais:\n"
    "1) Responder perguntas teóricas sobre controle e PID\n"
    "2) Simular o comportamento da planta com parâmetros fornecidos\n"
    "3) Otimizar os parâmetros do controlador para melhorar o desempenho\n\n"
    "Dada a mensagem do usuário, retorne SOMENTE um JSON no formato:\n"
    "{\n"
    '  "decisao": "TEORIA" | "SIMULAR" | "OTIMIZAR",\n'
    '  "kp": float | null,\n'
    '  "ki": float | null,\n'
    '  "kd": float | null,\n'
    '  "ganho_alvo": float | null,\n'
    '  "erro_alvo": float | null\n'
    "}\n\n"
    "Regras de classificação:\n"
    "- **TEORIA**: perguntas conceituais sobre controle, PID ou comportamento de sistemas.\n"
    "- **SIMULAR**: quando o usuário fornece valores de controlador e deseja ver o comportamento da planta. "
    "Valores podem ser ZERO (0) e devem ser mantidos.\n"
    "- **OTIMIZAR**: quando o usuário quer encontrar automaticamente os parâmetros do controlador.\n"
    "Se um parâmetro não estiver presente na mensagem, retorne null."
)


class TriagemOut(BaseModel):
    decisao: Literal["TEORIA", "SIMULAR", "OTIMIZAR"]
    kp: Optional[float] = None
    ki: Optional[float] = None
    kd: Optional[float] = None
    ganho_alvo: Optional[float] = None
    erro_alvo: Optional[float] = None


triagem_chain = llm.with_structured_output(TriagemOut, method="json_mode")


def triagem(mensagem):
    saida: TriagemOut = triagem_chain.invoke([
        SystemMessage(content=TRIAGEM_PROMPT),
        HumanMessage(content=mensagem),
    ])
    return saida.model_dump()

"""### Testando só a triagem (antes de montar o grafo)
"""

testes = [
    "o que é overshoot em sistemas de controle?",
    "simule a planta com kp=1.5 ki=0.1 kd=0.05",
    "otimize os parâmetros do PID para minimizar erro",
]

for msg_teste in testes:
    print(f"Pergunta: {msg_teste}\n -> Resposta: {triagem(msg_teste)}\n")


class AgentState(TypedDict, total=False):
    pergunta: str
    classificacao: str
    parametros: dict
    resultado: dict
    resposta_tecnica: str
    resposta: str
    citacoes: list
    comentario_operador: str  # comentário da LLM sobre a etapa em execução


def comentar_operador(nome_no, contexto):
    """Pede à LLM um comentário técnico para o operador, narrando o que o
    sistema acabou de fazer nesta etapa — pode ter até 10 linhas, com
    detalhes relevantes (valores, decisões, observações técnicas).
    Separado da resposta final que vai para o chat — é só para dar
    visibilidade do processo em tempo real na interface."""
    prompt = f"""
Você é a camada de narração de um painel de controle industrial. Escreva um
comentário técnico para o operador, em português, explicando o que o sistema
acabou de fazer nesta etapa.

Regras:
- Até 10 linhas. Pode ser mais curto se não houver necessidade de mais texto.
- Tom técnico, direto, como um relatório de painel — sem cumprimentos, sem
  emojis, sem markdown pesado (nada de #, **, listas com marcadores).
- Não diga literalmente "estou no nó X" — descreva a ação e, quando fizer
  sentido, o porquê da decisão ou o que os valores obtidos significam.
- Baseie-se apenas no contexto abaixo, sem inventar números que não estejam
  ali.

Etapa do sistema: {nome_no}
Contexto: {contexto}

Escreva o comentário agora.
"""
    try:
        resposta = llm.invoke(prompt)
        return resposta.content.strip()
    except Exception:
        return f"Executando etapa: {nome_no}."


def node_triagem(state: AgentState) -> AgentState:
    print("\n🔎 [NÓ] triagem — classificando a pergunta...", flush=True)
    saida = triagem(state["pergunta"])
    classificacao = saida["decisao"].upper().strip()
    print("Classificação:", classificacao, flush=True)
    parametros = {
        "kp": saida.get("kp"), "ki": saida.get("ki"), "kd": saida.get("kd"),
        "ganho_alvo": saida.get("ganho_alvo"), "erro_alvo": saida.get("erro_alvo"),
    }
    comentario = comentar_operador(
        "triagem",
        f"pergunta do usuário: '{state['pergunta']}'. Classificada como "
        f"{classificacao}. Parâmetros extraídos da mensagem: {parametros}.",
    )
    print(f"💬 {comentario}", flush=True)
    return {
        **state, "classificacao": classificacao, "parametros": parametros,
        "comentario_operador": comentario,
    }


def node_teoria(state: AgentState) -> AgentState:
    print("\n📚 [NÓ] teoria (RAG) — buscando contexto nos PDFs...", flush=True)
    pergunta = state["pergunta"]
    rag_resp = perguntar_controle_rag(pergunta)
    print("RAG encontrou contexto:", rag_resp["contexto_encontrado"], flush=True)

    if rag_resp["contexto_encontrado"]:
        resposta_final, citacoes = rag_resp["answer"], rag_resp["citacoes"]
    else:
        prompt = f"""
Você é um especialista em sistemas de controle em malha fechada.

Explique a pergunta abaixo de forma clara para um estudante de engenharia elétrica.

Pergunta:
{pergunta}

Observação:
Não foram encontrados documentos na base de conhecimento.
Responda com base apenas no conhecimento geral de engenharia de controle.
"""
        resposta_llm = llm.invoke(prompt)
        resposta_final, citacoes = resposta_llm.content, []

    comentario = comentar_operador(
        "teoria",
        f"pergunta teórica: '{pergunta}'. Contexto encontrado nos PDFs da "
        f"base de conhecimento: {rag_resp['contexto_encontrado']}.",
    )
    print(f"💬 {comentario}", flush=True)
    return {**state, "resposta": resposta_final, "citacoes": citacoes, "comentario_operador": comentario}


def node_simular(state: AgentState) -> AgentState:
    print("\n⚙️ [NÓ] simular — rodando o PID em malha fechada...", flush=True)
    p = state["parametros"]
    kp = p.get("kp") if p.get("kp") is not None else 1.0
    ki = p.get("ki") if p.get("ki") is not None else 0.1
    kd = p.get("kd") if p.get("kd") is not None else 0.05
    resultado_final = simular_planta(kp, ki, kd, protecao_overshoot=True)
    print("⚙️ [NÓ] simular — concluído.", flush=True)

    comentario = comentar_operador(
        "simular",
        f"simulação em malha fechada concluída. Ganhos usados: "
        f"Kp={resultado_final['Kp']:.2f} Ki={resultado_final['Ki']:.2f} "
        f"Kd={resultado_final['Kd']:.2f}. Overshoot={resultado_final['overshoot']}%, "
        f"tempo de acomodação={resultado_final['tempo_acomod']}s, "
        f"erro final={resultado_final['erro_final']}. Ganhos solicitados pelo "
        f"usuário: Kp={kp}, Ki={ki}, Kd={kd} (se diferentes dos usados, é "
        f"porque a proteção contra overshoot reduziu os ganhos).",
    )
    print(f"💬 {comentario}", flush=True)
    return {**state, "resultado": resultado_final, "comentario_operador": comentario}


def node_otimizar(state: AgentState) -> AgentState:
    print("\n🧠 [NÓ] otimizar — iniciando grid search com critérios de convergência...", flush=True)
    melhor_final = buscar_melhores_parametros(
        geracoes_sem_melhora_max=8,
        geracoes_valor_repetido_max=5,
        tolerancia=0.5,
    )
    print("🧠 [NÓ] otimizar — concluído.", flush=True)

    if melhor_final:
        contexto = (
            f"grid search concluído. Melhor combinação encontrada: "
            f"Kp={melhor_final['Kp']:.2f} Ki={melhor_final['Ki']:.2f} "
            f"Kd={melhor_final['Kd']:.2f}. Overshoot={melhor_final['overshoot']}%, "
            f"tempo de acomodação={melhor_final['tempo_acomod']}s, "
            f"erro final={melhor_final['erro_final']}, ISE={melhor_final['ise']}."
        )
    else:
        contexto = "grid search concluído sem encontrar nenhuma combinação válida."
    comentario = comentar_operador("otimizar", contexto)
    print(f"💬 {comentario}", flush=True)
    return {**state, "resultado": melhor_final, "comentario_operador": comentario}


def node_resposta_final(state: AgentState) -> AgentState:
    print("\n📊 [NÓ] resposta_final — calculando métricas...", flush=True)
    r = state["resultado"]
    texto = f"""
Simulação PID realizada.

Parâmetros do controlador:
Kp = {r["Kp"]}
Ki = {r["Ki"]}
Kd = {r["Kd"]}

Métricas:
Overshoot: {r["overshoot"]} %
Tempo de acomodação: {r["tempo_acomod"]} s
Erro final: {r["erro_final"]}

ISE: {r["ise"]}
IAE: {r["iae"]}
ITAE: {r["itae"]}
"""
    comentario = comentar_operador(
        "resposta_final",
        f"métricas consolidadas para apresentação: overshoot={r['overshoot']}%, "
        f"tempo de acomodação={r['tempo_acomod']}s, erro final={r['erro_final']}, "
        f"ISE={r['ise']}, IAE={r['iae']}, ITAE={r['itae']}.",
    )
    print(f"💬 {comentario}", flush=True)
    return {**state, "resposta_tecnica": texto, "comentario_operador": comentario}


def node_llm(state: AgentState) -> AgentState:
    print("\n🤖 [NÓ] llm — refinando texto da resposta...", flush=True)
    classificacao = state.get("classificacao")

    if classificacao in ("SIMULAR", "OTIMIZAR"):
        texto = state.get("resposta_tecnica", "")
        acao = "SIMULAÇÃO" if classificacao == "SIMULAR" else "OTIMIZAÇÃO"
        prompt = f"""
Você é um especialista em sistemas de controle industrial.

Abaixo está o resultado de uma {acao} de um controlador PID que já foi
executada. Use exatamente essa palavra ({acao.lower()}) ao se referir ao que
foi feito — não troque por outro termo.

Apresente esse resultado de forma limpa, mantendo EXATAMENTE os valores
numéricos informados (não invente nem arredonde diferente do que está aqui).

Adicione um comentário técnico ESPECÍFICO sobre este
resultado (por exemplo, se o overshoot está alto, se o erro final é
satisfatório, se a sintonia parece adequada).

NÃO explique conceitos gerais de controle PID (o que é Kp, Ki, Kd, overshoot,
ISE, IAE, ITAE etc.) — o usuário já pediu uma {acao.lower()}, não uma aula de
teoria. Seja direto e objetivo.

Resultado:
{texto}
"""
    else:
        texto = state.get("resposta_tecnica", state.get("resposta", ""))
        prompt = f"""
Você é um especialista em sistemas de controle.

Explique o conteúdo abaixo de forma clara e didática, em texto corrido e
tabelas quando fizer sentido.

NÃO inclua seções como "resumo visual", "diagrama", "esquema" ou qualquer
tentativa de desenhar um diagrama/gráfico usando apenas texto ou caracteres
ASCII — isso não é um diagrama de verdade, só texto tentando parecer um, e
fica quebrado. Se quiser ilustrar algo visualmente, descreva em palavras ou
use uma tabela.

{texto}
"""
    resposta = llm.invoke(prompt)
    print("🤖 [NÓ] llm — concluído.", flush=True)
    comentario = "Resposta final formatada e entregue ao operador no console."
    return {**state, "resposta": resposta.content, "comentario_operador": comentario}


workflow = StateGraph(AgentState)
workflow.add_node("triagem", node_triagem)
workflow.add_node("simular", node_simular)
workflow.add_node("teoria", node_teoria)
workflow.add_node("otimizar", node_otimizar)
workflow.add_node("resposta_final", node_resposta_final)
workflow.add_node("llm", node_llm)

workflow.add_edge(START, "triagem")
workflow.add_conditional_edges(
    "triagem", lambda x: x["classificacao"],
    {"SIMULAR": "simular", "TEORIA": "teoria", "OTIMIZAR": "otimizar"},
)
workflow.add_edge("simular", "resposta_final")
workflow.add_edge("otimizar", "resposta_final")
workflow.add_edge("resposta_final", "llm")
workflow.add_edge("teoria", "llm")
workflow.add_edge("llm", END)

app = workflow.compile()

"""### Fluxograma do agente
"""

from IPython.display import Image, display

graph_bytes = app.get_graph().draw_mermaid_png()
display(Image(graph_bytes))

"""### Testando o agente completo
"""

#pergunta = "simule a planta com kp=4 ki=0.1 kd=0.05"
pergunta = "otimize a planta"

resultado = app.invoke({"pergunta": pergunta}, config={"recursion_limit": 10})

print("\n" + "=" * 30)
print("RESPOSTA DO SISTEMA")
print("=" * 30 + "\n")
print(resultado["resposta"])

"""## Bloco V — Interface
"""

!pip install -q gradio

import base64
import io
import time

import gradio as gr
from PIL import Image

# ---------------------------------------------------------------------------
# Tema e CSS — painel industrial escuro (texto com contraste maior)
# ---------------------------------------------------------------------------
TEMA_INDUSTRIAL = gr.themes.Base(
    primary_hue=gr.themes.colors.amber,
    secondary_hue=gr.themes.colors.slate,
    neutral_hue=gr.themes.colors.slate,
    font=[gr.themes.GoogleFont("Roboto Mono"), "ui-monospace", "monospace"],
    text_size=gr.themes.sizes.text_lg,
).set(
    body_background_fill="#0a0a0a",
    body_background_fill_dark="#0a0a0a",
    background_fill_primary="#111214",
    background_fill_primary_dark="#111214",
    background_fill_secondary="#0d0e10",
    background_fill_secondary_dark="#0d0e10",
    border_color_primary="#3a3d44",
    border_color_primary_dark="#3a3d44",
    block_background_fill="#141518",
    block_background_fill_dark="#141518",
    block_border_color="#3a3d44",
    block_border_color_dark="#3a3d44",
    block_label_background_fill="#1c1e22",
    block_label_background_fill_dark="#1c1e22",
    block_label_text_color="#ffc061",
    block_label_text_color_dark="#ffc061",
    block_title_text_color="#ffffff",
    block_title_text_color_dark="#ffffff",
    body_text_color="#eaeaea",
    body_text_color_dark="#eaeaea",
    body_text_color_subdued="#b5b9c0",
    body_text_color_subdued_dark="#b5b9c0",
    button_primary_background_fill="#f5a623",
    button_primary_background_fill_hover="#ffb84d",
    button_primary_text_color="#0a0a0a",
    button_primary_border_color="#f5a623",
    input_background_fill="#0d0e10",
    input_background_fill_dark="#0d0e10",
    input_border_color="#3a3d44",
    input_border_color_dark="#3a3d44",
    input_border_color_focus="#f5a623",
    input_border_color_focus_dark="#f5a623",
    input_placeholder_color="#8a8f98",
    input_placeholder_color_dark="#8a8f98",
    shadow_drop="none",
)

CSS_INDUSTRIAL = """
#painel-titulo {
    background: linear-gradient(180deg, #1a1b1e 0%, #0d0e10 100%);
    border: 1px solid #3a3d44;
    border-left: 4px solid #f5a623;
    border-radius: 4px;
    padding: 14px 18px;
    margin-bottom: 10px;
}
#painel-titulo h2 {
    letter-spacing: 1.5px;
    text-transform: uppercase;
    color: #ffc061 !important;
    margin: 0 !important;
    font-size: 22px !important;
}
#painel-titulo p {
    color: #c7cbd1 !important;
    margin: 4px 0 0 0 !important;
    font-size: 14px !important;
    letter-spacing: 0.5px;
}
.gradio-container {
    background: #0a0a0a !important;
    font-size: 15px !important;
}
.gr-box, .block {
    border-radius: 4px !important;
}
label span {
    letter-spacing: 0.5px;
    text-transform: uppercase;
    font-size: 13px !important;
    color: #ffffff !important;
    font-weight: 700 !important;
}

/* texto das mensagens do chat (bolha do assistente, fundo escuro) */
.message, .message p, .message li {
    font-size: 15px !important;
    line-height: 1.5 !important;
    color: #f0f0f0 !important;
}
.message strong { color: #ffc061 !important; }

/* bolha de mensagem do usuário — fundo claro (âmbar suave), texto precisa ser escuro */
.message.user,
.message.user p,
.message.user li,
.message.user span,
[data-testid="user"] .message,
[data-testid="user"] .message p {
    color: #1a1a1a !important;
}
.message.user strong {
    color: #4a3400 !important;
}

/* caixa de digitar */
textarea, input[type="text"] {
    font-size: 15px !important;
    color: #f5f5f5 !important;
}
textarea::placeholder, input[type="text"]::placeholder {
    color: #9a9fa8 !important;
    opacity: 1 !important;
}

/* painel de métricas */
.painel-metricas {
    background: #0d0e10;
    border: 1px solid #3a3d44;
    border-radius: 4px;
    padding: 12px 16px;
    font-family: "Roboto Mono", monospace;
    font-size: 14px;
}
.linha-metrica {
    display: flex;
    justify-content: space-between;
    padding: 5px 0;
    border-bottom: 1px dashed #2f3238;
    color: #f0f0f0;
    letter-spacing: 0.4px;
}
.linha-metrica:last-child {
    border-bottom: none;
}
.linha-metrica span:first-child {
    color: #b5b9c0;
    text-transform: uppercase;
    font-size: 12px;
}
.linha-metrica span:last-child {
    color: #4ade80;
    font-weight: 700;
    font-size: 14px;
}

/* painel de comentários do agente — texto mais longo, várias linhas */
.painel-comentarios {
    background: #0d0e10;
    border: 1px solid #3a3d44;
    border-radius: 4px;
    padding: 12px 16px;
    font-family: "Roboto Mono", monospace;
    font-size: 13px;
    max-height: 320px;
    overflow-y: auto;
}
.comentario-vazio {
    color: #9a9fa8;
    font-style: italic;
}
.bloco-comentario {
    padding: 8px 0;
    border-bottom: 1px dashed #2f3238;
}
.bloco-comentario:last-child {
    border-bottom: none;
}
.tag-no {
    display: inline-block;
    color: #0a0a0a;
    background: #f5a623;
    font-weight: 700;
    font-size: 10px;
    letter-spacing: 0.5px;
    text-transform: uppercase;
    padding: 2px 7px;
    border-radius: 3px;
    margin-bottom: 5px;
}
.texto-comentario {
    color: #e5e5e5;
    line-height: 1.55;
    white-space: pre-line;
}
"""

# ---------------------------------------------------------------------------
# Diagrama do workflow — estilo "quadro de comando" com LEDs
# ---------------------------------------------------------------------------
NOS_WORKFLOW = [
    ("triagem",        "TRIAGEM"),
    ("teoria",         "TEORIA · RAG"),
    ("simular",        "SIMULAR"),
    ("otimizar",       "OTIMIZAR"),
    ("resposta_final", "RESP. TÉCNICA"),
    ("llm",            "LLM"),
]

# (cor de fundo do card, cor do LED, cor do texto)
CORES_STATUS = {
    "idle":      ("#181a1e", "#5a5f68", "#c2c6cc"),
    "ativo":     ("#241f10", "#f5a623", "#ffd889"),
    "concluido": ("#0f2116", "#34d980", "#8ff2b4"),
    "pulado":    ("#141315", "#4a3a40", "#79707a"),
}


def status_iniciais():
    return {chave: "idle" for chave, _ in NOS_WORKFLOW}


def marcar_pulados(status_nos, classificacao):
    ramos = {"teoria": "TEORIA", "simular": "SIMULAR", "otimizar": "OTIMIZAR"}
    for no, rotulo in ramos.items():
        if rotulo != classificacao:
            status_nos[no] = "pulado"
    return status_nos


def renderizar_workflow(status_nos):
    blocos = []
    for i, (chave, rotulo) in enumerate(NOS_WORKFLOW):
        status = status_nos.get(chave, "idle")
        fundo, cor_led, cor_texto = CORES_STATUS[status]
        pulso = "animation: piscar 1s ease-in-out infinite;" if status == "ativo" else ""
        seta = "" if i == 0 else '<span style="color:#5a5f68;font-size:16px;margin:0 2px;">&rsaquo;</span>'
        blocos.append(f"""
            {seta}
            <div style="
                background:{fundo}; border:1px solid #3a3d44; border-top:2px solid {cor_led};
                border-radius:3px; padding:10px 14px; margin:3px; min-width:126px;
                display:inline-flex; align-items:center; gap:8px; font-size:13px;
                letter-spacing:0.6px; text-transform:uppercase; font-weight:700;
                color:{cor_texto}; box-shadow: inset 0 0 12px rgba(0,0,0,0.4);">
                <span style="width:9px;height:9px;border-radius:50%;background:{cor_led};
                    box-shadow:0 0 7px {cor_led};{pulso}display:inline-block;flex-shrink:0;"></span>
                {rotulo}
            </div>""")
    return f"""
    <style>
    @keyframes piscar {{
        0%, 100% {{ opacity: 1; box-shadow: 0 0 6px #f5a623; }}
        50% {{ opacity: 0.35; box-shadow: 0 0 2px #f5a623; }}
    }}
    </style>
    <div style="
        background:#0d0e10; border:1px solid #3a3d44; border-radius:4px;
        padding:10px 8px; display:flex; flex-wrap:wrap; align-items:center;">
        {"".join(blocos)}
    </div>
    """


def base64_para_imagem(grafico_b64):
    if not grafico_b64:
        return None
    return Image.open(io.BytesIO(base64.b64decode(grafico_b64)))


def formatar_metricas(resultado):
    if not resultado:
        return '<div class="painel-metricas">SEM SIMULAÇÃO DISPONÍVEL</div>'
    linhas = [
        ("OVERSHOOT", f"{resultado.get('overshoot', '-')} %"),
        ("TEMPO DE ACOMODAÇÃO", f"{resultado.get('tempo_acomod', '-')} s"),
        ("ERRO FINAL", f"{resultado.get('erro_final', '-')}"),
        ("ISE", f"{resultado.get('ise', '-')}"),
        ("IAE", f"{resultado.get('iae', '-')}"),
        ("ITAE", f"{resultado.get('itae', '-')}"),
    ]
    linhas_html = "".join(
        f'<div class="linha-metrica"><span>{rotulo}</span><span>{valor}</span></div>'
        for rotulo, valor in linhas
    )
    return f'<div class="painel-metricas">{linhas_html}</div>'


def renderizar_comentarios(comentarios):
    """comentarios: lista de tuplas (nome_no, texto_comentario)."""
    if not comentarios:
        return (
            '<div class="painel-comentarios">'
            '<span class="comentario-vazio">Aguardando pergunta do operador…</span>'
            '</div>'
        )
    blocos = "".join(
        f"""
        <div class="bloco-comentario">
            <span class="tag-no">{no}</span>
            <div class="texto-comentario">{texto}</div>
        </div>
        """
        for no, texto in comentarios
    )
    return f'<div class="painel-comentarios">{blocos}</div>'


# ---------------------------------------------------------------------------
# Função principal: roda o agente nó a nó, atualizando o painel
# ---------------------------------------------------------------------------
def responder(pergunta, historico):
    if not pergunta or not pergunta.strip():
        yield historico, renderizar_workflow(status_iniciais()), gr.update(), gr.update(), renderizar_comentarios([]), ""
        return

    historico = historico + [{"role": "user", "content": pergunta}]
    status_nos = status_iniciais()
    comentarios = []

    yield historico, renderizar_workflow(status_nos), gr.update(), gr.update(), renderizar_comentarios(comentarios), gr.update()

    estado_final = {}
    for evento in app.stream({"pergunta": pergunta}, config={"recursion_limit": 10}):
        for nome_no, saida_no in evento.items():
            for chave, _ in NOS_WORKFLOW:
                if status_nos.get(chave) == "ativo":
                    status_nos[chave] = "concluido"
            status_nos[nome_no] = "ativo"

            if nome_no == "triagem":
                classificacao = saida_no.get("classificacao")
                status_nos = marcar_pulados(status_nos, classificacao)

            comentario = saida_no.get("comentario_operador")
            if comentario:
                comentarios.append((nome_no, comentario))

            estado_final.update(saida_no)
            yield historico, renderizar_workflow(status_nos), gr.update(), gr.update(), renderizar_comentarios(comentarios), gr.update()
            time.sleep(0.4)

    for chave, _ in NOS_WORKFLOW:
        if status_nos.get(chave) == "ativo":
            status_nos[chave] = "concluido"

    resposta = estado_final.get("resposta", "Não consegui gerar uma resposta.")
    historico = historico + [{"role": "assistant", "content": resposta}]

    resultado = estado_final.get("resultado")
    imagem = base64_para_imagem(resultado["grafico"]) if resultado else gr.update()
    metricas = formatar_metricas(resultado) if resultado else gr.update()

    yield historico, renderizar_workflow(status_nos), imagem, metricas, renderizar_comentarios(comentarios), ""


# ---------------------------------------------------------------------------
# Layout
# ---------------------------------------------------------------------------
with gr.Blocks(title="SCP-01 · Painel de Controle PID", theme=TEMA_INDUSTRIAL, css=CSS_INDUSTRIAL) as demo:

    with gr.Column(elem_id="painel-titulo"):
        gr.Markdown("## SCP-01 · Assistente de Controle PID")
        gr.Markdown("Sistema de distribuição de água — planta RNA + controlador PID + agente de IA")

    with gr.Row():
        with gr.Column(scale=1):
            gr.Markdown("**CONSOLE DO OPERADOR**")
            chatbot = gr.Chatbot(label=None, height=430, show_label=False)
            pergunta_input = gr.Textbox(
                placeholder="> simule com kp=1.5 ki=0.1 kd=0.05", show_label=False
            )
            botao_enviar = gr.Button("EXECUTAR", variant="primary")

        with gr.Column(scale=1):
            gr.Markdown("**WORKFLOW DO AGENTE**")
            workflow_html = gr.HTML(renderizar_workflow(status_iniciais()))

            gr.Markdown("**COMENTÁRIOS DO AGENTE**")
            comentarios_html = gr.HTML(renderizar_comentarios([]))

            gr.Markdown("**RESPOSTA DA PLANTA**")
            imagem_grafico = gr.Image(
                value=base64_para_imagem(resultados.get("grafico")),
                show_label=False,
                interactive=False,
                container=True,
            )
            metricas_html = gr.HTML(formatar_metricas(resultados))

    entradas = [pergunta_input, chatbot]
    saidas = [chatbot, workflow_html, imagem_grafico, metricas_html, comentarios_html, pergunta_input]

    pergunta_input.submit(responder, entradas, saidas)
    botao_enviar.click(responder, entradas, saidas)

demo.queue()
demo.launch(share=True, debug=False)